Small Docker additions
SyneRBI/SIRF-SuperBuild pull request #463
Opened 2021-01-01 19:20 UTC by KrisThielemans

updated README and make it easier to run the devel image.

2021-01-01 23:03 UTC, casperdcl requested changes

2021-01-01 23:03 UTC, casperdcl commented on docker/docker-compose.devel.yml
> +   #target: sirf
```suggestion
```

2021-01-01 23:03 UTC, casperdcl commented on docker/docker-compose.devel.yml
> +   - ./devel/gadgetron_data:/tmp/gadgetron_data
```suggestion
```

2021-01-01 23:03 UTC, casperdcl commented on docker/sirf-compose-devel
> +docker-compose -f docker-compose.devel.yml -f docker-compose.nix.yml "$@"
```suggestion
./sirf-compose -f docker-compose.devel.yml "$@"
```

2021-01-01 23:04 UTC, casperdcl commented on docker/docker-compose.devel.yml
> +  container_name: sirf  # for scaling, comment this out https://github.com/docker/compose/issues/3729
this is a patch file so this duplication should be removed

2021-01-01 23:04 UTC, casperdcl commented on docker/docker-compose.devel.yml
> +   USER_ID: ${UID:-1000}
this is a patch file so this duplication should be removed

2021-01-01 23:04 UTC, casperdcl commented on docker/docker-compose.devel.yml
> +   #target: sirf
this is a patch file so this duplication should be removed

2021-01-01 23:04 UTC, casperdcl commented on docker/docker-compose.devel.yml
> +   - ./devel/gadgetron_data:/tmp/gadgetron_data
this is a patch file so this duplication should be removed

2021-01-01 23:06 UTC, casperdcl commented on docker/sirf-compose-devel
> +docker-compose -f docker-compose.devel.yml -f docker-compose.nix.yml "$@"
optionally, add new file(s) `sirf-compose-server-devel*` etc identical to current `sirf-compose-server*` except using `./sirf-compose-devel` instead of `./sirf-compose`...

2021-01-02 09:21 UTC, KrisThielemans commented on docker/README.md
> +```
ok

2021-01-02 09:21 UTC, KrisThielemans commented on docker/README.md
> +```
left-over. thanks for spotting this

2021-01-02 09:21 UTC, KrisThielemans commented on docker/sirf-compose-devel
> +docker-compose -f docker-compose.devel.yml -f docker-compose.nix.yml "$@"
I understand the patch file concept now. great!

2021-01-03 21:09 UTC, casperdcl commented on docker/README.md
> +resume working next time by using `start` again (start-up will also be a lot faster).
is this really true? It's not meant to be the case... since SIRF-Exercises are cloned to the shared `devel` folder it should be fairly quick the second time...

2021-01-04 19:04 UTC, KrisThielemans commented on docker/README.md
> +resume working next time by using `start` again (start-up will also be a lot faster).
it is, but could be related to various items, including #464 and https://github.com/SyneRBI/SIRF-SuperBuild/discussions/462#discussioncomment-256669

2021-01-21 08:21 UTC, merged