Add Gadgetron dependency
SyneRBI/SIRF-SuperBuild pull request #503
Opened 2021-03-16 16:10 UTC by johannesmayer

This PR is just a test to see if Travis succeeds in building with Gadgetron as a dependency for SIRF.
Problem is that Travis does not build the SIRF-PR because SIRF and Gadgetron are built simultaneously.

2021-03-16 16:30 UTC, KrisThielemans requested changes

2021-03-16 16:30 UTC, KrisThielemans commented on SuperBuild/External_SIRF.cmake
> +    set(${proj}_DEPENDENCIES "${${prof}_DEPENEDCIES};Gadgetron")
```suggestion
    set(${proj}_DEPENDENCIES "${${proj}_DEPENDENCIES};Gadgetron")
```

2021-03-16 16:30 UTC, KrisThielemans commented on version_config.cmake
> +set(DEFAULT_SIRF_URL https://github.com/johannesmayer/SIRF.git )
can't have that later on of course

2021-03-16 16:30 UTC, KrisThielemans commented on version_config.cmake
> +  set (DEFAULT_SIRF_TAG origin/rpe-encoding)
as above

2021-03-16 16:30 UTC, KrisThielemans commented on SuperBuild/External_CCPi-Framework.cmake
> +      INSTALL_COMMAND ${CMAKE_COMMAND} --build . --target install && ${CMAKE_COMMAND} -E copy_directory ${${proj}_SOURCE_DIR}/Wrappers/Python/data ${SUPERBUILD_INSTALL_DIR}/share/cil/ && ${PYTHON_EXE
are you sure about this?

2021-03-16 16:49 UTC, KrisThielemans commented on SuperBuild/External_SIRF.cmake
> +    set(${proj}_DEPENDENCIES "${${proj}_DEPENEDCIES};Gadgetron")
still wrong

2021-03-16 16:50 UTC, johannesmayer commented on SuperBuild/External_CCPi-Framework.cmake
> +      INSTALL_COMMAND ${CMAKE_COMMAND} --build . --target install && ${CMAKE_COMMAND} -E copy_directory ${${proj}_SOURCE_DIR}/Wrappers/Python/data ${SUPERBUILD_INSTALL_DIR}/share/cil/ && ${PYTHON_EXE
I don't understand what is correct. This location is different between the CCPi-Framework `master` branch and the tag `v20.09.1` which is always checked out on my VM. 

I reverted it, s.t. if CCPi-Framework `origin/master` is checked out it is correct.

2021-03-16 16:52 UTC, johannesmayer commented on SuperBuild/External_SIRF.cmake
> +    set(${proj}_DEPENDENCIES "${${proj}_DEPENEDCIES};Gadgetron")
Git damnit, I'm sorry :D

2021-03-16 16:57 UTC, KrisThielemans commented on SuperBuild/External_CCPi-Framework.cmake
> +      INSTALL_COMMAND ${CMAKE_COMMAND} --build . --target install && ${CMAKE_COMMAND} -E copy_directory ${${proj}_SOURCE_DIR}/Wrappers/Python/data ${SUPERBUILD_INSTALL_DIR}/share/cil/ && ${PYTHON_EXE
@paskino could advice I guess

2021-03-16 20:28 UTC, KrisThielemans commented
The first job failed, but that's a xenial build that always fails #501 . However, the `DEVEL` build fails as well with https://travis-ci.com/github/SyneRBI/SIRF-SuperBuild/jobs/491517076#L25296
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

Please set them or make sure they are set and tested correctly in the CMake files:
GT_CPUCORE
    linked by target "cgadgetron" in directory /home/travis/build/SyneRBI/SIRF-SuperBuild/sources/SIRF/src/xGadgetron/cGadgetron
GT_FFT
    linked by target "cgadgetron" in directory /home/travis/build/SyneRBI/SIRF-SuperBuild/sources/SIRF/src/xGadgetron/cGadgetron
GT_LOG
    linked by target "cgadgetron" in directory /home/travis/build/SyneRBI/SIRF-SuperBuild/sources/SIRF/src/xGadgetron/cGadgetron
GT_NFFT
    linked by target "cgadgetron" in directory /home/travis/build/SyneRBI/SIRF-SuperBuild/sources/SIRF/src/xGadgetron/cGadgetron
```
I guess that's a problem in your PR.

I suggest that you revert the lines that point to your PR and only keep the dependency update. Then we can merge this one, and you can keep tinkering away on the PR.

2021-03-16 21:33 UTC, johannesmayer commented
Thanks for the suggestion, I can do that.

2021-03-17 09:45 UTC, paskino commented on SuperBuild/External_CCPi-Framework.cmake
> +      INSTALL_COMMAND ${CMAKE_COMMAND} --build . --target install && ${CMAKE_COMMAND} -E copy_directory ${${proj}_SOURCE_DIR}/Wrappers/Python/data ${SUPERBUILD_INSTALL_DIR}/share/cil/ && ${PYTHON_EXE
Up to CIL 20.09 the python package lived under `ccpi`, from version 20.11 we have changed it to `cil`. So there is a backward incompatibility for CIL. 
In master the CIL version is [20.11.2](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/version_config.cmake#L166)

Finally I don't understand why the line had to be changed, but I suspect it is a local problem on @johannesmayer 's installation.

2021-03-17 09:48 UTC, johannesmayer commented on SuperBuild/External_CCPi-Framework.cmake
> +      INSTALL_COMMAND ${CMAKE_COMMAND} --build . --target install && ${CMAKE_COMMAND} -E copy_directory ${${proj}_SOURCE_DIR}/Wrappers/Python/data ${SUPERBUILD_INSTALL_DIR}/share/cil/ && ${PYTHON_EXE
yes that's correct. My SuperBuild checks out the old CIL tag and so it fails. I just don't change it here.

2021-03-17 10:03 UTC, paskino commented
I just found the reason of the failure: the dependency on Gadgetron was added if `BUILD_GADGETRON` flag was true, but the correct spelling is `BUILD_Gadgetron`. So it would always return false and never add Gadgetron in the pre-requisites.

2021-03-17 13:37 UTC, paskino commented
The build worked now, but the unit tests fail with this error
```
ImportError: /home/travis/build/SyneRBI/SIRF-SuperBuild/INSTALL/python/sirf/_pygadgetron.so: undefined symbol: cGT_getGRPETrajecotry
```

2021-03-17 13:40 UTC, johannesmayer commented
Ok thanks for the hint, I will sort it out... apparently the exclusion of non-cartesian code is still imperfect 👎

2021-03-17 13:45 UTC, paskino commented
but that error is coming from the `DEVEL_BUILD=ON`, that is when you build the RPE encoding, oder?

2021-03-17 13:46 UTC, johannesmayer commented
that is correct

2021-03-22 18:41 UTC, KrisThielemans commented
perfect! if you now revert the `version_config` changes, this should be good to merge in my opinion

2021-03-23 09:21 UTC, johannesmayer commented
I checked again and saw that the tests [unfortunately] took less than 10 minutes now and they succeeded. 
I hope that the line I added to avoid Travis timeout actually works when they take longer because it is the only line of "Travis code" that I ever wrote.

2021-03-23 10:18 UTC, KrisThielemans commented
> I hope that the line I added to avoid Travis timeout actually works when they take longer because it is the only line of "Travis code" that I ever wrote.

I don't really know, but
```
/3 Test #3: SIRF_TESTS .......................   Passed  636.00 sec
```
looks good :-)

Please add a line in `CHANGES` (with `[ci skip]').

ok to squash-merge this one?

2021-03-23 10:50 UTC, johannesmayer commented
Yes please, squash merge.

2021-03-23 10:57 UTC, KrisThielemans approved these changes

2021-03-23 11:00 UTC, merged