Build GitHub action
SyneRBI/SIRF-SuperBuild pull request #513
Opened 2021-04-07 16:59 UTC by paskino

Creates a GitHub for CI.

Although it only checks one configuration, it is better than none as we have now in the SuperBuild.

2021-04-07 17:21 UTC, paskino commented
The build was [successful](https://github.com/paskino/SIRF-SuperBuild/runs/2289222005?check_suite_focus=true) in my fork.

2021-04-07 17:48 UTC, KrisThielemans requested changes
Looks great.

you'll have to merge `master` of course due to the conflict. (it might prevent running the action)

2021-04-07 17:48 UTC, KrisThielemans commented on .github/workflows/c-cpp.yml
> +          cmake --build . -j 2;
not sure what they recommend for parallel builds

2021-04-07 17:48 UTC, KrisThielemans commented on docker/build_python-ubuntu.sh
>  set -ev
are you sure about the permission change for this file? (I didn't check what the numbers mean)

2021-04-07 17:48 UTC, KrisThielemans commented on docker/ctest_sirf.sh
> +export PATH=/home/runner/.local/bin:$PATH
using `/home/runner` probably makes it specific to Github actions. Could be useful for docker tests etc as well obviously. Possibly `${HOME}` works

2021-04-07 17:48 UTC, KrisThielemans commented on docker/ctest_sirf.sh
> +source ~/devel/install/bin/activate
```suggestion
source ${INSTALL_DIR}/bin/activate 
```

2021-04-07 17:48 UTC, KrisThielemans commented on docker/ctest_sirf.sh
> +${INSTALL_DIR}/bin/gadgetron >& gadgetron.log&
```suggestion
gadgetron >& gadgetron.log&
```
as it's already in the path

2021-04-07 17:48 UTC, KrisThielemans commented on docker/user_python-ubuntu.sh
>  if [ -f requirements.txt ]; then
permission change in this file as well

2021-04-07 17:57 UTC, paskino commented on docker/user_python-ubuntu.sh
>  if [ -f requirements.txt ]; then
stupid windows!

2021-04-07 17:58 UTC, paskino commented on docker/ctest_sirf.sh
> +export PATH=/home/runner/.local/bin:$PATH
My plan is to move this whole thing to docker container, but since I got it running, I though to add it to the SuperBuild as it is (with changes) so that we have a form of CI

2021-04-07 18:39 UTC, KrisThielemans commented on docker/ctest_sirf.sh
> +export PATH=/home/runner/.local/bin:$PATH
for sure, although I wouldn't say we're only going to do CI via docker builds. At least, that doesn't look like a good idea to me (although not sure).

whatever path we follow, I certainly agree that we have to do this in stages of course. I just wondered if using `$HOME` wouldn't immediately generalise it, but feel free to postpone to later if you're not sure.

2021-04-07 18:40 UTC, KrisThielemans commented on docker/user_python-ubuntu.sh
>  if [ -f requirements.txt ]; then
strange, I don't think my "git for windows" does that.

2021-04-08 06:38 UTC, paskino commented on .github/workflows/c-cpp.yml
> +          cmake --build . -j 2;
so far so good!

2021-04-08 06:57 UTC, paskino commented on docker/ctest_sirf.sh
> +source ~/devel/install/bin/activate
virtualenv is installed in [`~/devel/install`](https://github.com/paskino/SIRF-SuperBuild/blob/build-github-action/.github/workflows/c-cpp.yml#L24)

2021-04-08 07:23 UTC, paskino commented on docker/build_python-ubuntu.sh
>  set -ev
no, this is because I edited on windows and sometimes this happens...
fixed

2021-04-08 07:24 UTC, paskino commented on docker/user_python-ubuntu.sh
>  if [ -f requirements.txt ]; then
I don't know, this happens to me. I'm using Visual Studio Code and git from cygwin, a poisonous mixture?

2021-04-08 07:27 UTC, paskino commented on docker/ctest_sirf.sh
> +export PATH=/home/runner/.local/bin:$PATH
What I meant is that this action is using all the docker scripts but re-bundles them together. It'd be better to use them as they were meant to, although @casperdcl is using them with docker compose.

If I'm confused by docker, docker compose sets the bar even higher.

2021-04-08 07:29 UTC, paskino commented
Let's wait for the [action](https://github.com/paskino/SIRF-SuperBuild/actions/runs/728654439) to run and be green then we can merge?

2021-04-08 07:42 UTC, KrisThielemans requested changes

2021-04-08 07:42 UTC, KrisThielemans commented on docker/ctest_sirf.sh
> +fi
```suggestion
fi
exit $test_fail
```
Otherwise we don't get the correct test status

2021-04-08 08:11 UTC, KrisThielemans commented
What about trying `ccache` already? Seems simple enough
```
- name: ccache
  uses: hendrikmuhs/ccache-action@v1
...

- name: build
  run: |
    export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
     ...
```

2021-04-08 08:13 UTC, KrisThielemans commented
Please also edit `CHANGES.md`. Most important is probably to say that the Docker build moved to `python3`. (a bit surprising to have that in this PR, what about change the title of this PR to say "Add GitHub action and use Python3 in docker"?)

2021-04-08 09:21 UTC, paskino commented
> What about trying `ccache` already? Seems simple enough
> 
> ```
> - name: ccache
>   uses: hendrikmuhs/ccache-action@v1
> ...
> 
> - name: build
>   run: |
>     export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
>      ...
> ```

I need to know what `ccache` is ...

Let me know when to merge.

2021-04-08 09:39 UTC, KrisThielemans commented
`ccache` is "easy". it works behind the scenes to keep a cache of compilations, such that the next build could be 10 times faster. Highly recommended to install it on your system (and if it's in the path, CMake will find it).

but we can put those lines in a 2nd PR of course., so if you feel like (squash)merging now, go ahead.

2021-04-08 10:15 UTC, merged

2021-04-08 10:24 UTC, casperdcl commented on docker/ctest_sirf.sh
> +export PATH=/home/runner/.local/bin:$PATH
`docker-compose` is a replacement for `make` really. Except it's specific to `docker` and it works on any OS.