build ACE Armadillo and Boost
SyneRBI/SIRF-SuperBuild pull request #663
Opened 2022-03-06 21:17 UTC by paskino

test CI

2022-03-07 08:25 UTC, paskino commented
Problem 1: `cblas.h` is not found.

`cblas.h` is part of [`libatlas-dev`](https://packages.ubuntu.com/bionic/amd64/libatlas-base-dev/filelist), however it can be seen that the file has the name `cblas-atlas.h`. 

In my Ubuntu 18.04 which I use to test the SuperBuild these builds don't fail and I have the following files:

```
ls -lh /usr/include/x86_64-linux-gnu/
total 316K
-rw-r--r-- 1 root root 4.3K Jan 24 12:53 a.out.h
drwxr-xr-x 2 root root  12K Feb 22 06:00 asm
drwxr-xr-x 2 root root  12K Jan 24  2020 atlas
drwxr-xr-x 3 root root  20K Mar  2 06:43 bits
drwxr-xr-x 4 root root 4.0K Jan 25  2021 c++
-rw-r--r-- 1 root root  34K Sep 13  2017 cblas-atlas.h
-rw-r--r-- 1 root root  21K Jun 17  2017 cblas_f77.h
lrwxrwxrwx 1 root root   42 Jan 24  2020 cblas.h -> /etc/alternatives/cblas.h-x86_64-linux-gnu
-rw-r--r-- 1 root root  444 Nov 28  2017 cblas_mangling.h
-rw-r--r-- 1 root root  30K Nov 28  2017 cblas-netlib.h
-rw-r--r-- 1 root root  45K Sep 19  2017 cblas-openblas.h
-rw-r--r-- 1 root root 9.5K Sep 13  2017 clapack.h
-rw-r--r-- 1 root root 3.5K Feb 17 23:38 expat_config.h
-rw-r--r-- 1 root root  47K Sep 19  2017 f77blas.h
-rw-r--r-- 1 root root 3.5K Jan 24 12:53 fpu_control.h
drwxr-xr-x 2 root root 4.0K Mar  2 06:43 gnu
-rw-r--r-- 1 root root 4.8K Jan 24 12:53 ieee754.h
-rw-r--r-- 1 root root 2.2K Jun  4  2020 jconfig.h
drwxr-xr-x 2 root root 4.0K Jan 24  2020 libxslt
-rw-r--r-- 1 root root 4.7K Sep 19  2017 openblas_config.h
drwxr-xr-x 2 root root 4.0K Mar  5  2021 python2.7
drwxr-xr-x 2 root root 4.0K Dec 17 06:37 python3.6m
drwxr-xr-x 2 root root  12K Mar  2 06:43 sys
```

`cblas.h` is a symbolic link to a file that seems to have been created by `update-alternatives`. 
Looking into the file I get 

```
#ifndef CBLAS_H
#define CBLAS_H

#include <stddef.h>
#include "openblas_config.h"
...
```
That means that this `cblas.h` is part of OpenBLAS, and `diff` confirms that.

2022-03-07 08:35 UTC, KrisThielemans commented
I did see somewhere a recommendation to install `openblas`.

2022-03-07 10:08 UTC, paskino commented
[Error ](https://github.com/SyneRBI/SIRF-SuperBuild/runs/5445683784?check_suite_focus=true#step:7:29487)building `siemens_to_ismrmrd`

```
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/siemens_to_ismrmrd/XNode.cpp:39:22: error: expected primary-expression before ‘const’
  BOOST_FOREACH(XNode const& cnode, node.children_) {
                      ^~~~~
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/siemens_to_ismrmrd/XNode.cpp:39:2: error: ‘BOOST_FOREACH’ was not declared in this scope
  BOOST_FOREACH(XNode const& cnode, node.children_) {
  ^~~~~~~~~~~~~
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/siemens_to_ismrmrd/XNode.cpp:39:2: note: suggested alternative: ‘BOOST_FINAL’
  BOOST_FOREACH(XNode const& cnode, node.children_) {
  ^~~~~~~~~~~~~
  BOOST_FINAL
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/siemens_to_ismrmrd/XNode.cpp: In member function ‘std::__cxx11::string XProtocol::getXMLString::operator()(const XProtocol::XNodeParamMap&) const’:
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/siemens_to_ismrmrd/XNode.cpp:98:22: error: expected primary-expression before ‘const’
  BOOST_FOREACH(XNode const& cnode, node.children_) {
                      ^~~~~
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/siemens_to_ismrmrd/XNode.cpp:98:2: error: ‘BOOST_FOREACH’ was not declared in this scope
  BOOST_FOREACH(XNode const& cnode, node.children_) {
  ^~~~~~~~~~~~~
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/siemens_to_ismrmrd/XNode.cpp:98:2: note: suggested alternative: ‘BOOST_FINAL’
  BOOST_FOREACH(XNode const& cnode, node.children_) {
  ^~~~~~~~~~~~~
  BOOST_FINAL
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/siemens_to_ismrmrd/XNode.cpp: In member function ‘std::__cxx11::string XProtocol::getXMLString::operator()(const XProtocol::XNodeParamArray&) const’:
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/siemens_to_ismrmrd/XNode.cpp:115:22: error: expected primary-expression before ‘const’
  BOOST_FOREACH(XNode const& cnode, node.children_) {
                      ^~~~~
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/siemens_to_ismrmrd/XNode.cpp:115:2: error: ‘BOOST_FOREACH’ was not declared in this scope
  BOOST_FOREACH(XNode const& cnode, node.children_) {
  ^~~~~~~~~~~~~
/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/siemens_to_ismrmrd/XNode.cpp:115:2: note: suggested alternative: ‘BOOST_FINAL’
  BOOST_FOREACH(XNode const& cnode, node.children_) {
  ^~~~~~~~~~~~~
  BOOST_FINAL
```

2022-03-07 17:01 UTC, KrisThielemans commented
this seems to get into a nightmare. What about forgetting about building BOOST ourselves? Installing that is easy enough on all platforms. We can sort that out later.

Same for ACE and Armadillo I guess, but possibly easier.

2022-03-07 21:01 UTC, paskino commented
In fact, the last build [without ](https://github.com/SyneRBI/SIRF-SuperBuild/runs/5452484862?check_suite_focus=true)`siemens_to_ismrmrd` has completed correctly while building ACE, Boost and Armadillo.

2022-03-08 13:29 UTC, paskino commented
See also https://github.com/ismrmrd/siemens_to_ismrmrd/issues/92

2022-03-09 22:46 UTC, KrisThielemans requested changes
still ISMRMRD 1.5.0 at https://github.com/SyneRBI/SIRF-SuperBuild/blob/8afee138baf6989bbf7770a687437ba52862eb91/version_config.cmake#L111

2022-03-09 22:46 UTC, KrisThielemans commented on version_config.cmake
> +  set(DEFAULT_siemens_to_ismrmrd_TAG origin/master)
this will come and bite us. I'd prefer to fix a version here

2022-03-10 09:21 UTC, paskino commented
I think this is ready for re-review. I will remove the references to my branch and merge if approved.
One of the CI config failed at install prerequisite phase.

2022-03-10 09:42 UTC, KrisThielemans commented on docker/user_sirf-ubuntu.sh
> +: ${SIRF_SB_TAG=check_build_build_boost}
I don't know why you modified this in this PR as `user_sirf-ubuntu.sh` isn't used on GHA (only in docker and the VM), but will have to revert it as you say.

2022-03-10 09:46 UTC, KrisThielemans requested changes
looks great. tiny comment

2022-03-10 09:50 UTC, KrisThielemans commented on CHANGES.md
> +  - siemens_to_ismrmrd: [b87759e49e53dab4939147eb52b7a0e6465f3d04](https://github.com/ismrmrd/siemens_to_ismrmrd/commit/b87759e49e53dab4939147eb52b7a0e6465f3d04)
probably helpful to say `> 1.7.0 with bug-fix for boost/foreach.hpp`

2022-03-11 11:10 UTC, paskino commented on docker/user_sirf-ubuntu.sh
> +: ${SIRF_SB_TAG=check_build_build_boost}
because I'm confused. And it's me who created the GHA (initially)! Probably it went out of hand, certainly.

2022-03-11 15:05 UTC, KrisThielemans approved these changes
squash merge please

2022-03-11 17:41 UTC, merged