Fix python dest bashrc
SyneRBI/SIRF-SuperBuild pull request #692
Opened 2022-04-19 13:35 UTC by paskino

closes #691

2022-04-19 14:10 UTC, paskino commented
Additional problem: the call

https://github.com/SyneRBI/SIRF-SuperBuild/blob/fcea2e436551802326716a0420052ee171f22c2c/docker/user_python-ubuntu.sh#L14


calls  the following code:

```bash
#!/bin/sh
_CONDA_ROOT="/opt/pyvenv"
# Copyright (C) 2012 Anaconda, Inc
# SPDX-License-Identifier: BSD-3-Clause
\. "$_CONDA_ROOT/etc/profile.d/conda.sh" || return $?
conda activate "$@"
```
In this case `$@` will expand to the parameters passed to `user_python-ubuntu.sh`. Unfortunately this is not correct as activate will only work if passed a name of an environment and certainly not if passed 2 parameters, which return 

```
conda activate "$@"
++ conda activate /opt/conda miniconda
++ local cmd=activate
++ case "$cmd" in
++ __conda_activate activate /opt/conda miniconda
++ '[' -n '' ']'
++ local ask_conda
+++ PS1='sirf$ '
+++ __conda_exe shell.posix activate /opt/conda miniconda
+++ __add_sys_prefix_to_path
+++ '[' -n '' ']'
++++ dirname /opt/conda/bin/conda
+++ SYSP=/opt/conda/bin
++++ dirname /opt/conda/bin
+++ SYSP=/opt/conda
+++ '[' -n '' ']'
+++ PATH=/opt/conda/bin:/opt/conda/condabin:/usr/lib/ccache:/opt/cmake/bin:/usr/                                                         local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/u                                                         sr/bin:/sbin:/bin:/home/jovyan/.local/bin
+++ export PATH
+++ /opt/conda/bin/conda shell.posix activate /opt/conda miniconda
activate does not accept more than one argument:
['/opt/conda', 'miniconda']
```

2022-04-19 16:28 UTC, paskino commented
Any idea on how to achieve this @KrisThielemans @ashgillman ?

Additionally, I was thinking to pass these info as temporary environment variables:

`PYTHON_EXECUTABLE='sa' PYTHON_INSTALL_DIR="/opt/pyvenv" bash test_my_vars.sh`

with `test_my_vars.sh` as 

```bash

if [ -n PYTHON_EXECUTABLE ]; then 
  PYTHON='miniconda'
else
  PYTHON=$PYTHON_EXECUTABLE
fi

if [ -n PYTHON_INSTALL_DIR ]; then
  INSTALL_DIR="/opt/conda"
else
  INSTALL_DIR=${PYTHON_INSTALL_DIR}
fi

echo "PYTHON_EXECUTABLE ${PYTHON}"
echo "PYTHON_INSTALL_DIR ${INSTALL_DIR}"
```

but my output is 
```
PYTHON_EXECUTABLE miniconda
PYTHON_INSTALL_DIR /opt/conda
```
while I expected

```
PYTHON_EXECUTABLE sa
PYTHON_INSTALL_DIR /opt/pyvenv
```

2022-04-19 21:23 UTC, KrisThielemans commented
The `activate` problem.
==============
Not sure why they have `$@` in a script to be sourced. Seems to make no sense to me. What's in `"$_CONDA_ROOT/etc/profile.d/conda.sh" `?
I suppose you could cheat and just replace the `source .../activate` line with the 2 lines that it actually contains (but removing the `$@`).

The environment problem
=================
I believe you need (probably with the quotes, not 100% sure)
```sh
if [ -n "$PYTHON_EXECUTABLE" ]; then
...
```

2022-04-20 08:10 UTC, paskino commented
Thanks, the environment problem is due to my poor knowledge of bash! I missed a `$` and inverted the test case! It should be

```bash 

if [ -n "${PYTHON_EXECUTABLE}" ]; then 
  PYTHON=$PYTHON_EXECUTABLE
else
  PYTHON='miniconda'
fi

if [[ -n "${PYTHON_INSTALL_DIR}" ]]; then
  INSTALL_DIR=${PYTHON_INSTALL_DIR}
else
  INSTALL_DIR="/opt/conda"
fi

echo "PYTHON_EXECUTABLE ${PYTHON}"
echo "PYTHON_INSTALL_DIR ${INSTALL_DIR}"
```

Double quotes are not necessary.

2022-04-20 08:13 UTC, KrisThielemans commented
> Double quotes are not necessary.

are you sure? suppose the path contains a space?

2022-04-20 13:07 UTC, paskino commented
You are right, they were not necessary to fix my problem, but they are needed to prevent the problem of a path with a space!

2022-04-20 13:59 UTC, paskino commented
Some checks fail on [building CIL](https://github.com/SyneRBI/SIRF-SuperBuild/runs/6095484623?check_suite_focus=true#step:7:2055), however other configurations build CIL, both in devel and no devel config.

The error unveils something weird: `cmake` is being passed/passing the wrong path. Apparently it thinks that the `CMAKE_CURRENT_BUILD_DIRECTORY` is `/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/CIL/Wrappers/Python/` which doesn't make sense.

```
CMake Error at Wrappers/Python/cmake_install.cmake:54 (file):
  file INSTALL cannot find
  "/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/CIL/Wrappers/Python/build/lib/cil":
  No such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:48 (include)
```

2022-04-20 14:25 UTC, KrisThielemans requested changes
typo

2022-04-20 14:25 UTC, KrisThielemans commented on docker/user_python-ubuntu.sh
> +# Fx`xor details see https://github.com/SyneRBI/SIRF-SuperBuild/pull/692#issuecomment-1102704682
```suggestion
# For details see https://github.com/SyneRBI/SIRF-SuperBuild/pull/692#issuecomment-1102704682 
```

2022-04-20 14:29 UTC, KrisThielemans commented
> The error unveils something weird: `cmake` is being passed/passing the wrong path. Apparently it thinks that the `CMAKE_CURRENT_BUILD_DIRECTORY` is `/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/CIL/Wrappers/Python/` which doesn't make sense.

can you point to the CIL CMake file? The SB one has the line https://github.com/SyneRBI/SIRF-SuperBuild/blob/fcea2e436551802326716a0420052ee171f22c2c/SuperBuild/External_CIL.cmake#L63
I cannot see anything wrong with that (nor related to the error)

2022-04-20 14:58 UTC, paskino commented
Sure, this is for the non devel build. https://github.com/TomographicImaging/CIL/blob/f5c06566215564ad78ba0f1738d0836f3ad37a60/Wrappers/Python/CMakeLists.txt#L99-L100

2022-04-20 16:55 UTC, KrisThielemans commented
I note https://github.com/TomographicImaging/CIL/blob/f5c06566215564ad78ba0f1738d0836f3ad37a60/Wrappers/Python/CMakeLists.txt#L81-L82 but this is for `WIN32`, and is therefore presumably irrelevant. (Can't say I understand why you'd want to do that for WIN32, but it's up to you).

In any case, this seems unrelated to this PR, so ok to merge from my side

2022-04-22 08:17 UTC, paskino commented
Oh yes, that's a remnant of some previous code. In fact the install command is exactly the same for `WIN32` or not.

2022-04-22 11:27 UTC, paskino commented
ah no! that seems to be a bug https://github.com/TomographicImaging/CIL/issues/1226

2022-04-22 12:39 UTC, merged