Ismrmrd min required
SyneRBI/SIRF-SuperBuild pull request #693
Opened 2022-04-25 10:51 UTC by paskino

closes #635 

sets required versions for STIR and NIFTYREG

2022-04-25 17:12 UTC, KrisThielemans requested changes

2022-04-25 17:12 UTC, KrisThielemans commented on SuperBuild.cmake
> +endif()
```suggestion
set(STIR_REQUIRED_VERSION "4.1.0" CACHE STRING ON)
```
nice and simple. However, these lines should go into `version_config.cmake`

2022-04-25 17:12 UTC, KrisThielemans commented on SuperBuild.cmake
> +if (USE_SYSTEM_siemens_to_ismrmrd)
probably needs to be
```cmake
if (BUILD_siemens_to_ismrmrd)
```
also should be in `version_config.cmake`

2022-04-25 17:12 UTC, KrisThielemans commented on SuperBuild.cmake
> +set(parallelproj_REQUIRED_VERSION "0.8" CACHE STRING ON)
also should be in `version_config.cmake`

2022-04-25 20:10 UTC, paskino commented on SuperBuild.cmake
> +if (USE_SYSTEM_siemens_to_ismrmrd)
I believe `BUILD_siemens_to_ismrmrd = NOT USE_SYSTEM_siemens_to_ismrmrd`.

2022-04-25 20:11 UTC, paskino commented on SuperBuild.cmake
> +endif()
Of course we can always add the `${proj}_REQUIRED_VERSION` which will be used only in the case we use the system `${proj}`

2022-04-25 20:37 UTC, KrisThielemans commented on SuperBuild.cmake
> +if (USE_SYSTEM_siemens_to_ismrmrd)
no, not as far as I can see. In fact, `USE_SYSTEM_siemens_to_ismrmrd` is nowhere used. Even stronger, it should not exist as a `USE_SYSTEM*` variable only makes sense for "library" type of projects. I would remove it.

2022-04-25 20:42 UTC, KrisThielemans reviewed
Should the `*REQUIRED_VERSION` be cached variables? These are not "user-settable", except in somewhat contrived cases (example: someone sets e.g .`SIRF_TAG` to a lower version, *and* is using a system ISMRMRD version that is older than what would be required).

We could keep it cached, but then I would certainly make them `ADVANCED`. But I'd prefer not to have them cached: otherwise we'd have one more set of variables to delete when upgrading .

2022-04-26 06:10 UTC, KrisThielemans commented on version_config.cmake
> +  endif()
```suggestion
  if (BUILD_siemens_to_ismrmrd)
    set(ISMRMRD_REQUIRED_VERSION "1.7")
  else()
    set(ISMRMRD_REQUIRED_VERSION "1.4.2.1")
  endif()
```

2022-04-26 06:12 UTC, KrisThielemans commented
Build failures is probably due to https://github.com/TomographicImaging/CIL/issues/1226

2022-04-26 06:13 UTC, KrisThielemans commented
If you're happy with my suggestion, please squash-merge.

2022-04-26 06:31 UTC, paskino commented on SuperBuild.cmake
> +if (USE_SYSTEM_siemens_to_ismrmrd)
Ah, all right

2022-04-26 06:43 UTC, paskino commented
I had not noticed the existence of `BUILD_siemens_to_ismrmrd` but did notice `USE_SYSTEM_siemens_to_ismrmrd`. 

CIL bugfix is [going to be merged](https://github.com/TomographicImaging/CIL/pull/1227) and I will bump the version/commit as soon as it is merged.

2022-04-26 06:46 UTC, merged