Fix gadgetron link
SyneRBI/SIRF-SuperBuild pull request #711
Opened 2022-05-16 09:41 UTC by paskino

As described in #709 there are problem resolving libraries at runtime and at build time. This PR tries to address this.

2022-05-16 10:52 UTC, paskino commented
I'm not sure about the `.bashrc`. I think that's a problem but maybe it has nothing to do with this PR.

2022-05-16 15:24 UTC, KrisThielemans reviewed
I really don't know if using `USE_SYSTEM_HDF5=OFF` is a good idea. As opposed to having 2 hdf5 builds (`apt` and `conda`), we will now have 3...

Of course, we should be able to safely set `LD_LIBRARY_PATH` to our builds (as opposed to the one from `conda`). However, presumably that means that conda installed code that uses hdf5 will break. Or maybe not, as conda's `python` presumably adds conda lib directories to its path, but then the SIRF build could break...

I think this all points to a serious problem in HDF5 shared libraries. It seems there is no foolproof way around this.

2022-05-16 15:24 UTC, KrisThielemans commented on docker/user_sirf-ubuntu.sh
> +cmake --build . -j ${NUM_PARALLEL_BUILDS} --target
empty `--target`?

2022-05-16 15:32 UTC, KrisThielemans commented
Alternative 1:
------------
create a script (`gadgetron.sh` or even `sirf_gadgetron.sh`) which sets `LD_LIBRARY_PATH` appropriately and runs it. 

pros:
- no extra HDF5 library
- nobody else is affected.

cons:
- you have to remember to call that script
- presumably any SIRF (or STIR) executable that needs HDF5 libraries would need the same treatment, which becomes unmanageable.

Alternative 2:
-------------
build with `USE_SYSTEM_HDF5=on` but make sure gadgetron, STIR and SIRF get linked with the system version.

pros:
- no extra HDF5 library
- no need for `LD_LIBRARY_PATH`

cons:
- not sure what will happen in Python

2022-05-16 16:16 UTC, KrisThielemans commented
There's of course

Alternative 3
-------------
use `RPATH` for everything. Could work very well on `docker` as we have complete control.

2022-05-16 19:44 UTC, paskino commented on docker/user_sirf-ubuntu.sh
> +cmake --build . -j ${NUM_PARALLEL_BUILDS} --target
wrong!

2022-05-16 19:47 UTC, paskino commented
CIL uses `h5py` which in turn uses `HDF5` library. These are installed by conda and get linked with `RPATH`. So, I'd argue that the conda packages will be safe. As a matter of fact, we never had an issue with CIL use of HDF5 with SIRF.

2022-05-16 21:09 UTC, paskino commented on docker/user_sirf-ubuntu.sh
> +cmake --build . -j ${NUM_PARALLEL_BUILDS} --target
fixed now.

2022-05-17 07:16 UTC, paskino commented
If `USE_SYSTEM_HDF5=OFF` then the build works fine as we know where the libriaries are.
Option 3 is the best IMO. However, due to time constraints for the PSMRTBP training school, I'd like to merge this as is, possibly not closing the issue?

2022-05-17 07:23 UTC, KrisThielemans commented
Sure. Might have to be a squash merge as I guess history is very ugly here

2022-05-17 07:37 UTC, paskino commented
I always like to squash n merge

2022-06-09 10:39 UTC, KrisThielemans requested changes

2022-06-09 10:39 UTC, KrisThielemans commented on SuperBuild/External_Gadgetron.cmake
> +      -DCMAKE_BUILD_RPATH=".;${Gadgetron_INSTALL_DIR}/lib"
I'm not sure what the consequences of this are, but a `.`  seems terribly dangerous

2022-06-09 10:39 UTC, KrisThielemans commented on version_config.cmake
> +  set(DEFAULT_STIR_TAG release_5.0)
shouldn't be in this PR Note that 5.0.2 is out, so better to use that in a separate PR. see https://github.com/SyneRBI/SIRF-SuperBuild/pull/719

2022-08-18 20:20 UTC, KrisThielemans commented
I believe this is obsolete and should be abandoned

2023-01-16 14:59 UTC, KrisThielemans commented
Obsolete?

2023-03-05 19:02 UTC, paskino commented
Yes obsolete, closing

2023-03-05 19:02 UTC, closed without merging