Jupyterhub env
SyneRBI/SIRF-SuperBuild pull request #718
Opened 2022-05-19 16:32 UTC by paskino

This PR uses the branch I am currently utilising to build the jupyterhub image for the PSMRTBP2022 school.

closes #715 

However this PR changes slightly the use of `requirements.txt` and `requirements_conda_forge.txt`.
I introduced `requirements_conda_forge.txt` to be able to install prerequisites for CIL (mainly the Intel Performance Primitives library).

Probably we should use `requirements.txt` if `BUILD_CIL=OFF` or `BUILD_CIL_LITE=OFF`, and switch to requirements installed from `conda-forge` in case we build CIL. 

Some time ago, I also made so that CIL could be installed by conda, however maintaining this will be a problem because I see that we might need to have different requirements for the case we build CIL, we want CIL but not want to build it, etc.

So I propose that CIL can only be built by the SuperBuild.

2022-05-20 08:44 UTC, paskino commented
Also I am building with the following command
```bash 
 docker build --build-arg BASE_IMAGE=nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04 \
--build-arg PYTHON_INSTALL_DIR=/opt/conda \
--build-arg EXTRA_BUILD_FLAGS="-DBUILD_CIL=ON -DIPP_LIBRARY=/opt/conda/lib -DIPP_INCLUDE=/opt/conda/include -DSTIR_URL=https://github.com/paskino/STIR.git -DSTIR_TAG=bump_parallelproj" \
--build-arg SIRF_SB_URL="https://github.com/paskino/SIRF-SuperBuild.git" \
--build-arg SIRF_SB_TAG="jupyterhub_env" --build-arg NUM_PARALLEL_BUILDS=6 --target sirf .
```

2022-05-25 21:18 UTC, KrisThielemans commented on jupyterhub/Dockerfile
> +COPY --from=synerbi/sirf:sirf-core /opt/SIRF-SuperBuild/sources/SIRF/ /opt/SIRF-SuperBuild/sources/SIRF/
just curious. why?

2022-05-26 13:07 UTC, KrisThielemans commented on version_config.cmake
> +  set(DEFAULT_STIR_TAG release_5.0)
this will have to change to https://github.com/UCL/STIR/commit/40ede282ad39f87faaef015c92901db25796aa6c (done that in #719 )

2022-05-26 14:39 UTC, paskino commented on jupyterhub/Dockerfile
> +COPY --from=synerbi/sirf:sirf-core /opt/SIRF-SuperBuild/sources/SIRF/ /opt/SIRF-SuperBuild/sources/SIRF/
This is because we set `SIRF_PATH` that points to that directory.

2022-05-26 14:40 UTC, paskino commented on version_config.cmake
> +  set(DEFAULT_STIR_TAG release_5.0)
sure, for the training session, however in the build command I set a number of ad hoc versions.

https://github.com/paskino/SIRF-SuperBuild/tree/jupyterhub_env/jupyterhub#start-building-sirf

2022-05-26 15:07 UTC, KrisThielemans commented on jupyterhub/Dockerfile
> +COPY --from=synerbi/sirf:sirf-core /opt/SIRF-SuperBuild/sources/SIRF/ /opt/SIRF-SuperBuild/sources/SIRF/
@evgueni-ovtchinnikov I'm really not sure where `SIRF_PATH` is used. We install example data into `${CMAKE_INSTALL_PREFIX}/share/SIRF-3.2/data/` and similarly for `examples`. So I'd expect that `SIRF_PATH` should point to `${CMAKE_INSTALL_PREFIX}/share/SIRF-3.2/`. Obviously this isn't anything to fix now, but would be good to create a separate issue for this (SuperBuild I guess)

2022-05-26 15:09 UTC, KrisThielemans commented on version_config.cmake
> +  set(DEFAULT_STIR_TAG release_5.0)
yep, you're using `origin/master` for STIR. Sadly, I've just broken that (ctest will fail), but I guess you're not running its tests...

2022-05-26 15:25 UTC, paskino commented on jupyterhub/Dockerfile
> +COPY --from=synerbi/sirf:sirf-core /opt/SIRF-SuperBuild/sources/SIRF/ /opt/SIRF-SuperBuild/sources/SIRF/
Isn't it that `SIRF_PATH` is the path to SIRF's source code? It doesn't have anything to do with data, or am I mistaken?

These are the environment variables that I set in the image following [`env_sirf.sh`](https://github.com/SyneRBI/SIRF-SuperBuild/blob/jupyterhub_env/env_sirf.sh.in)

https://github.com/paskino/SIRF-SuperBuild/blob/1d5afcbc12179fed6f9858f937363c80efb34b8e/jupyterhub/Dockerfile#L50-L55

```Dockerfile

ENV PATH "/opt/conda/bin:/opt/SIRF-SuperBuild/INSTALL/bin:$PATH"
ENV LD_LIBRARY_PATH "/opt/SIRF-SuperBuild/INSTALL/lib:/opt/SIRF-SuperBuild/INSTALL/lib64:$LD_LIBRARY_PATH"
ENV PYTHONPATH "/opt/SIRF-SuperBuild/INSTALL/python"
ENV SIRF_INSTALL_PATH "/opt/SIRF-SuperBuild/INSTALL"
ENV SIRF_EXERCISES_DATA_PATH "/mnt/materials/SIRF/Fully3D/SIRF/"
ENV SIRF_PATH "/opt/SIRF-SuperBuild/sources/SIRF"
```

2022-05-26 15:46 UTC, KrisThielemans commented on version_config.cmake
> +  set(DEFAULT_STIR_TAG release_5.0)
fine for me. will have to update SIRF-Exercises later I guess

2023-01-23 09:13 UTC, paskino commented on version_config.cmake
> +  set(DEFAULT_STIR_TAG release_5.0)
updated to current SuperBuild Master which points to STIR 5.1.0

2023-01-23 09:29 UTC, KrisThielemans requested changes
a few things that I spotted that might help

2023-01-23 09:29 UTC, KrisThielemans commented on jupyterhub/README.md
> + docker build --build-arg BASE_IMAGE=nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04 --build-arg PYTHON_INSTALL_DIR=/opt/conda --build-arg EXTRA_BUILD_FLAGS="-DBUILD_CIL=ON -DIPP_LIBRARY=/opt/conda/lib -DI
18.04

2023-01-23 09:29 UTC, KrisThielemans commented on jupyterhub/README.md
> + nohup docker build --build-arg BASE_IMAGE=nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04 --build-arg PYTHON_INSTALL_DIR=/opt/conda --build-arg EXTRA_BUILD_FLAGS="-DBUILD_CIL=ON -DIPP_LIBRARY=/opt/conda/l
18.04

2023-01-23 09:29 UTC, KrisThielemans commented on jupyterhub/README.md
> +docker build --build-arg BASE_IMAGE=paskino/jupyter:datascience-notebook-cuda10-cudnn7-devel-ubuntu18.04 -f ../jupyterhub/Dockerfile .
18.04

2023-01-23 09:29 UTC, KrisThielemans commented on jupyterhub/README.md
> +Build of SIRF on Ubuntu 20.04 [fails](https://github.com/SyneRBI/SIRF-SuperBuild/issues/649)
outdated

2023-01-23 09:29 UTC, KrisThielemans commented on jupyterhub/README.md
> +
outdated

2023-01-23 09:33 UTC, KrisThielemans commented on jupyterhub/README.md
> + nohup docker build --build-arg BASE_IMAGE=nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04 --build-arg PYTHON_INSTALL_DIR=/opt/conda --build-arg EXTRA_BUILD_FLAGS="-DBUILD_CIL=ON -DIPP_LIBRARY=/opt/conda/l
oh sorry, it's a README. we wouldn't need these tags now. I'll resolve

2023-01-23 15:14 UTC, KrisThielemans commented
are we building ASTRA? Best for the intro notebooks.

By the way, I'm not sure that CIL dependencies are alright when building ASTRA (i.e. does it need to be guaranteed that ASTRA is built before CIL? i.e.
https://github.com/SyneRBI/SIRF-SuperBuild/blob/d50fce861da19374ddf989e4f8323b41b56f85af/SuperBuild/External_CIL.cmake#L24
might need an `if` on ASTRA

2023-01-23 15:18 UTC, KrisThielemans commented
I'm a bit surprised that all the actions are running. we're excluding `jupyterhub/**`. I thought for the docker-one could be because the white-space change in `Dockerfile`, but the others shouldn't run. oh well. Not important now, but if you don't know why this is happening, please create an issue for it after the dust settles.

2023-01-23 16:57 UTC, paskino commented
> does it need to be guaranteed that ASTRA is built before CIL?

CIL does not depend on ASTRA. We will use ASTRA if present. 

For SIRF usage it is not required. @ckolbPTB [introductory ](https://github.com/SyneRBI/SIRF-Exercises/blob/master/notebooks/Introductory/acquisition_model_mr_pet_ct.ipynb)notebook does not require ASTRA. The [gradient_descent ](https://github.com/SyneRBI/SIRF-Exercises/blob/master/notebooks/Synergistic/gradient_descent_mr_pet_ct.ipynb)one does, see https://github.com/SyneRBI/SIRF-Exercises/pull/192.

2023-01-23 17:05 UTC, KrisThielemans commented
> CIL does not depend on ASTRA. We will use ASTRA if present.

I agree, but if ASTRA is built after CIL, will it still be able to use it?

Why not build it on JupyterHub?  too late I guess.

> For SIRF usage it is not required. 

sure. https://github.com/SyneRBI/SIRF-Exercises/blob/master/notebooks/Introductory/acquisition_model_mr_pet_ct.ipynb uses it as well, although at least now it no longer fails as you've seen.

2023-01-23 17:10 UTC, paskino commented
I currently didn't add CIL to the jupyterhub image. I'll add it via conda if required. It is a 5 minute job. :D

2023-01-23 17:12 UTC, paskino commented
> if ASTRA is built after CIL, will it still be able to use it?

Yes, we only interact with ASTRA at the Python level so, as long as ASTRA and the python wrappers are built we can use it.

2023-01-23 17:18 UTC, KrisThielemans commented
> as long as ASTRA and the python wrappers are built we can use it.

yeah, but are they built if ASTRA isn't there?

2023-01-23 17:20 UTC, KrisThielemans commented
> I currently didn't add CIL to the jupyterhub image. I'll add it via conda if required. It is a 5 minute job. :D

well, if there's no CIL at all, even the intro stuff will fail, as we now just test on ASTRA.

I don't understand though. I thought you're grabbing the normal docker image, which has CIL. looks like i don't understand the jupyterhub stuff at all after all!

2023-01-23 17:37 UTC, KrisThielemans commented
https://github.com/SyneRBI/SIRF-SuperBuild/blob/fe6806f34586f0259e99ae0b639f9aa742d33d37/jupyterhub/Dockerfile#L1 is still 18.04

2023-01-23 17:39 UTC, KrisThielemans commented
https://github.com/SyneRBI/SIRF-SuperBuild/blob/fe6806f34586f0259e99ae0b639f9aa742d33d37/jupyterhub/Dockerfile#L50 says `Fully3D`. I don't care really, but just letting you know

2023-01-23 18:04 UTC, KrisThielemans commented
https://github.com/SyneRBI/SIRF-SuperBuild/blob/fe6806f34586f0259e99ae0b639f9aa742d33d37/jupyterhub/Dockerfile#L39-L40
`sirf-core`? Doesn't make sense to me. `core` doesn't have an `INSTALL`? I suppose that's your local name when building as the one on dockerhub is `sirf/core`. 

I guess it'd have to be `release-service-gpu`, except that is always going to point backwards. We currently don't seem to build `devel-service-gpu` (nor `devel-gpu`) on Travis, so we cannot pull from there.

I suppose this works for you, so no need to fix this now.

2023-01-25 04:07 UTC, KrisThielemans commented
`deprecation` isn't installed. Can't say I understand the installation of the dependencies anymore, but I'm sure @paskino does!

2023-01-25 07:41 UTC, KrisThielemans commented
`nbstripout` is not available, and there for the instructions fail. (I've updated the HackMD page)

2023-01-25 07:50 UTC, KrisThielemans commented
nibabel docopt also missing

2023-01-25 08:25 UTC, KrisThielemans commented
`parallelproj` isn't installed, so STIR doesn't have it (and neither does SIRF of course)

2023-01-25 11:01 UTC, paskino commented
> `deprecation` isn't installed. Can't say I understand the installation of the dependencies anymore, but I'm sure @paskino does!

Installed

2023-11-28 17:06 UTC, casperdcl requested changes

2023-11-28 17:06 UTC, casperdcl commented on jupyterhub/Dockerfile
>  FROM ${BASE_IMAGE} as base
```suggestion
ARG BASE_CONTAINER=nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04
FROM ${BASE_IMAGE} as base
```

just using `docker-stacks` convention

2023-11-28 17:06 UTC, casperdcl commented on jupyterhub/build_docker_stacks.sh
> +docker build --build-arg BASE_IMAGE=paskino/jupyter:datascience-notebook-cuda11-cudnn8-runtime-ubuntu22.04 -t paskino/jupyter:sirf -f jupyterhub/Dockerfile .
```suggestion

docker build --build-arg PYTHON_VERSION=3.9 --build-arg BASE_CONTAINER=nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu22.04 -t synerbi/jupyter:foundation .

cd ../base-notebook
docker build --build-arg BASE_CONTAINER=synerbi/jupyter:foundation -t synerbi/jupyter:base .

cd ../minimal-notebook
docker build --build-arg BASE_CONTAINER=synerbi/jupyter:base -t synerbi/jupyter:minimal .


cd ../scipy-notebook
docker build --build-arg BASE_CONTAINER=synerbi/jupyter:minimal -t synerbi/jupyter:scipy .

cd ../datascience-notebook
docker build --build-arg BASE_CONTAINER=synerbi/jupyter:scipy -t synerbi/jupyter:datascience .

popd

docker build --build-arg BASE_CONTAINER=synerbi/jupyter:datascience -t synerbi/jupyter:sirf -f jupyterhub/Dockerfile .
```

2023-11-28 21:31 UTC, casperdcl commented on jupyterhub/build_docker_stacks.sh
> +docker build --build-arg BASE_CONTAINER=synerbi/jupyter:datascience -t synerbi/jupyter:sirf -f jupyterhub/Dockerfile .
I guess this would be safest /CC @paskino

```suggestion
pushd "$(dirname "${BASH_SOURCE[0]}")"
git submodule update --init --recursive

cd docker-stacks/images/docker-stacks-foundation
docker build --build-arg PYTHON_VERSION=3.9 --build-arg BASE_CONTAINER=nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu22.04 -t synerbi/jupyter:foundation .

cd ../base-notebook
docker build --build-arg BASE_CONTAINER=synerbi/jupyter:foundation -t synerbi/jupyter:base .

cd ../minimal-notebook
docker build --build-arg BASE_CONTAINER=synerbi/jupyter:base -t synerbi/jupyter:minimal .


cd ../scipy-notebook
docker build --build-arg BASE_CONTAINER=synerbi/jupyter:minimal -t synerbi/jupyter:scipy .

cd ../datascience-notebook
docker build --build-arg BASE_CONTAINER=synerbi/jupyter:scipy -t synerbi/jupyter:datascience .

cd ..
docker build --build-arg BASE_CONTAINER=synerbi/jupyter:datascience -t synerbi/jupyter:sirf -f jupyterhub/Dockerfile .

popd
```

2023-11-28 22:34 UTC, casperdcl requested changes
just a bit concerned about which strategy is best:

1. copy SIRF installation dirs from `synerbi/sirf:latest` (CPU) image
2. copy SIRF installation dirs from `synerbi/sirf:service-gpu` (GPU) image
3. just build SIRF properly in the proposed `Dockerfile`

This PR currently does option (1), but I think (2) is safer, and (3) is best. btw option (3) also means we could perhaps deprecate the old SIRF images in favour of this new `docker-stacks` way?

2023-11-28 22:34 UTC, casperdcl commented on CHANGES.md
> +  - Ubuntu: 22.04 and nvidia/cuda:11.7.1-cudnn8-devel-ubuntu22.04
```suggestion
  - Ubuntu: 22.04 and nvidia/cuda:11.7.1-cudnn8-runtime-ubuntu22.04
```

2023-11-28 22:34 UTC, casperdcl commented on docker/requirements.yml
> +  - ccpi-regulariser
this would affect the old SIRF images too (not just the new docker-stacks images)... is that intended?

2023-11-28 22:34 UTC, casperdcl commented on jupyterhub/Dockerfile
> +    rm -rf ./scripts
this needs some cleanup

- remove commented lines
- why is `mamba env update -n base -f jupyterhub/requirements.yml` run twice
- why are some `mamba env update` commands run with explicit `-n base` and others aren't?

2023-11-28 22:34 UTC, casperdcl commented on jupyterhub/README.md
> -```
I removed this section @paskino but I'm concerned it doesn't match.

The removed readme text implies you have to rebuild SIRF images using `nvidia/cuda`... but in the proposed `Dockerfile` we just `COPY --from=synerbi/sirf:latest` (i.e. the CPU SIRF image). Is this ok?

2023-11-28 22:34 UTC, casperdcl commented on jupyterhub/README.md
> -docker build --build-arg BASE_IMAGE=nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04 --build-arg PYTHON_INSTALL_DIR=/opt/conda --build-arg EXTRA_BUILD_FLAGS="-DBUILD_CIL=ON -DIPP_LIBRARY=/opt/conda/lib -DIP
I also removed this section @paskino because in the proposed PR it seems CIL is just installed via `mamba`... is this correct?

2023-11-28 22:37 UTC, casperdcl commented
Also the new folder should be renamed `jupyterhub` -> `jupyter` because it has nothing to do with https://github.com/jupyterhub/jupyterhub

2023-11-28 22:37 UTC, casperdcl commented on jupyterhub/Dockerfile
btw this new folder should be renamed `jupyterhub` -> `jupyter` because it has nothing to do with https://github.com/jupyterhub/jupyterhub

2023-11-29 07:32 UTC, KrisThielemans commented on docker/Dockerfile
> + -DUSE_SYSTEM_Armadillo=ON -DUSE_SYSTEM_Boost=OFF\
related issue is #810, and I think therefore you're right.

2023-11-29 07:36 UTC, KrisThielemans commented on SuperBuild/External_Boost_configureboost.cmake
> +    --with-libraries=system,filesystem,thread,program_options,chrono,date_time,atomic,timer,regex,test,coroutine,context,random,python
more than likely needs to be reverted. This was put in as a stop-gap, see #810

2023-11-29 07:42 UTC, KrisThielemans commented on docker/requirements.yml
> +  - ccpi-regulariser
we came to a different conclusion in #836, but it might have been because we were in a rush

2023-11-29 07:42 UTC, KrisThielemans commented on docker/user_sirf-ubuntu.sh
> +set -v
probably bad idea to remove, as we do no error checking

2023-11-29 07:44 UTC, KrisThielemans commented
> just a bit concerned about which strategy is best:
> 
> 1. copy SIRF installation dirs from `synerbi/sirf:latest` (CPU) image
> 2. copy SIRF installation dirs from `synerbi/sirf:service-gpu` (GPU) image
> 3. just build SIRF properly in the proposed `Dockerfile`
> 
> This PR currently does option (1), but I think (2) is safer, and (3) is best. btw option (3) also means we could perhaps deprecate the old SIRF images in favour of this new `docker-stacks` way?

1&2 mix GPU versions, that seems weird, but in any case, I agree with you and prefer 3. The copy was done as a hack, but creates ugly dependencies.

2023-11-29 07:52 UTC, KrisThielemans commented
I can't find @casperdcl 's comment, but if docker-stacks allows merging the current `service` and `jupyterhub` images, that'd be a good thing...

2023-11-29 11:39 UTC, paskino commented on docker/requirements-service.yml
> +  - ipywidgets<8
It's a [CIL requirement](https://github.com/TomographicImaging/CIL/blob/be57697c96d3e66032bac5de5246d0d276e3ba1e/recipe/meta.yaml#L98) that conda does not comply with. See also https://github.com/TomographicImaging/CIL/pull/1599

2023-11-29 11:43 UTC, paskino commented on docker/requirements.yml
> +  - ccpi-regulariser
I don't know what would be best.

Earlier I stated https://github.com/SyneRBI/SIRF-SuperBuild/pull/718#issuecomment-1830317986 the opposite! I'm in a quantum state.

2023-11-29 11:44 UTC, paskino commented on jupyterhub/Dockerfile
> +    rm -rf ./scripts
mistakes, I suppose.

2023-11-29 11:54 UTC, paskino commented on jupyterhub/README.md
> -```
The thing is that when doing this I was building the GPU SIRF. And this doc was for me.

At the time I needed to build a specific branch/tag of SIRF(SuperBuild); these were the commands I used to build the SIRF image I required. Then I copied the files from such image to the docker-stack one.

2023-11-29 11:55 UTC, paskino commented on jupyterhub/README.md
> -docker build --build-arg BASE_IMAGE=nvidia/cuda:10.2-cudnn8-devel-ubuntu18.04 --build-arg PYTHON_INSTALL_DIR=/opt/conda --build-arg EXTRA_BUILD_FLAGS="-DBUILD_CIL=ON -DIPP_LIBRARY=/opt/conda/lib -DIP
I think that having this is important for when one wants to build a particular branch/tag of CIL which is not available as conda package.

2023-12-01 09:09 UTC, paskino commented
@KrisThielemans I guess you are referring to these comments https://github.com/SyneRBI/SIRF-SuperBuild/pull/718#pullrequestreview-1754056072 and https://github.com/SyneRBI/SIRF-SuperBuild/pull/718#issuecomment-1830317986 from @casperdcl 

If I understand correctly this PR will do:

1. create the base image containing the necessary stuff to run jupyter using the official [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks). Notice that they don't seem to have any release, just a master branch.
2. use the official (or built for purpose) SIRF docker image to install SIRF on the jupyter image
3. install CIL via conda dependencies that are scattered between SIRF-Exercises and SIRF-SuperBuild

I find 3 to be slighly concerning, because we need a CIL conda package if we want to install CIL now. I would like to retain the ability to build CIL via the SuperBuild and, in such case not install it via conda.

2023-12-01 11:57 UTC, KrisThielemans commented
> you are referring to these comments [#718 (review)](https://github.com/SyneRBI/SIRF-SuperBuild/pull/718#pullrequestreview-1754056072) and [#718 (comment)](https://github.com/SyneRBI/SIRF-SuperBuild/pull/718#issuecomment-1830317986) from @casperdcl

last one, yes

> I find 3 to be slighly concerning, because we need a CIL conda package if we want to install CIL now. I would like to retain the ability to build CIL via the SuperBuild and, in such case not install it via conda.

agreed, as per https://github.com/SyneRBI/SIRF-SuperBuild/issues/836#issuecomment-1739687386

Why do we "need a conda package to install CIL now"?

2024-01-03 14:17 UTC, casperdcl commented
> Why do we "need a conda package to install CIL now"?

/CC @paskino ?

> if docker-stacks allows merging the current `service` and `jupyterhub` images, that'd be a good thing...

Currently working on merging & greatly simplifying `docker` and `jupyterhub` folders, and ran into https://github.com/SyneRBI/SIRF-Exercises/pull/211 as well as #810 <- https://github.com/gadgetron/gadgetron/pull/1229... 

```sh
SIRF_SB_URL="https://github.com/SyneRBI/SIRF-SuperBuild" \
SIRF_SB_TAG="master" \
REMOVE_BUILD_FILES=1 \
RUN_CTEST=1 \
NUM_PARALLEL_BUILDS=" " \
BUILD_FLAGS="\
 -DCMAKE_BUILD_TYPE=Release\
 -DSTIR_ENABLE_OPENMP=ON -DUSE_SYSTEM_ACE=ON\
 -DUSE_SYSTEM_Armadillo=ON -DUSE_SYSTEM_Boost=??? \
 -DUSE_SYSTEM_FFTW3=ON -DUSE_SYSTEM_HDF5=OFF -DUSE_ITK=ON\
 -DUSE_SYSTEM_SWIG=ON\
 -DUSE_NiftyPET=OFF\
 -DBUILD_siemens_to_ismrmrd=ON -DBUILD_pet_rd_tools=ON" \
EXTRA_BUILD_FLAGS="-DGadgetron_USE_CUDA=ON -DBUILD_CIL=OFF -DUSE_SYSTEM_Boost=???" \
```
`bash` [`user_sirf-ubuntu.sh`](https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/docker/user_sirf-ubuntu.sh)


<details>
<summary>USE_SYSTEM_BOOST=OFF</summary>

```
...
-- Found PythonLibs: /opt/conda/lib/libpython3.9.so (found suitable version "3.9.18", minimum required is "3") 
-- Found Boost: /opt/SIRF-SuperBuild/INSTALL/lib/cmake/Boost-1.78.0/BoostConfig.cmake (found suitable version "1.78.0", minimum required is "1.65.0") found components: system program_options filesystem timer 
CMake Error at /opt/SIRF-SuperBuild/INSTALL/lib/cmake/Boost-1.78.0/BoostConfig.cmake:141 (find_package):
  Could not find a configuration file for package "boost_python" that exactly
  matches requested version "1.78.0".

  The following configuration files were considered but not accepted:

    /usr/lib/x86_64-linux-gnu/cmake/boost_python-1.74.0/boost_python-config.cmake, version: 1.74.0
    /lib/x86_64-linux-gnu/cmake/boost_python-1.74.0/boost_python-config.cmake, version: 1.74.0

Call Stack (most recent call first):
  /opt/SIRF-SuperBuild/INSTALL/lib/cmake/Boost-1.78.0/BoostConfig.cmake:262 (boost_find_component)
  /opt/cmake-3.25.1-linux-x86_64/share/cmake-3.25/Modules/FindBoost.cmake:594 (find_package)
  /opt/SIRF-SuperBuild/INSTALL/lib/cmake/gadgetron/gadgetron-config.cmake:36 (find_package)
  src/xGadgetron/cGadgetron/CMakeLists.txt:44 (find_package)
```

</details>

<details>
<summary>USE_SYSTEM_BOOST=ON</summary>

```
...
-- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.65.0") found components: system program_options filesystem timer
CMake Error at /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:141 (find_package):
  Found package configuration file:

    /usr/lib/x86_64-linux-gnu/cmake/boost_python-1.74.0/boost_python-config.cmake

  but it set boost_python_FOUND to FALSE so package "boost_python" is
  considered to be NOT FOUND.  Reason given by package:

  No suitable build variant has been found.

  The following variants have been tried and rejected:

  * libboost_python310.so.1.74.0 (3.10, Boost_PYTHON_VERSION=3.9)

  * libboost_python310.a (3.10, Boost_PYTHON_VERSION=3.9)

Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake:258 (boost_find_component)
  /opt/cmake-3.25.1-linux-x86_64/share/cmake-3.25/Modules/FindBoost.cmake:594 (find_package)
  /opt/SIRF-SuperBuild/INSTALL/lib/cmake/gadgetron/gadgetron-config.cmake:36 (find_package)
  src/xGadgetron/cGadgetron/CMakeLists.txt:44 (find_package)
```

</details>

any ideas?

2024-01-04 07:20 UTC, KrisThielemans commented
> Currently working on merging & greatly simplifying `docker` and `jupyterhub` folders, and ran into [SyneRBI/SIRF-Exercises#211](https://github.com/SyneRBI/SIRF-Exercises/pull/211) as well as #810 <- [gadgetron/gadgetron#1229](https://github.com/gadgetron/gadgetron/pull/1229)...

These are caused by Gadgetron-Python support. Easiest is to avoid it, for which we need https://github.com/gadgetron/gadgetron/pull/1229. This is now merged. Pretty much nothing has happened in Gadgetron except the very last commit, so I suggest trying to set  `Gadgetron_TAG=6202fb7352a14fb82817b57a97d928c988eb0f4b` (version of Oct 13, 2023).

However, *before* that merge, they merged https://github.com/gadgetron/gadgetron/pull/1225, which set ismrmrd=1.13.7, and siemens_to_ismrmrd=1.2.11, so we will need to update those versions as well (`DEFAULT_*_TAG`, not `REQUIRED`, as this is only for building them, no SIRF).

It might be best to do that in a separate PR.

Note that the `USE_SYSTEM_BOOST=OFF` case could alternatively be fixed by building Boost-Python, but as we don't Gadgetron's Python gadgets, I wouldn't go there.



> > Why do we "need a conda package to install CIL now"?
> 
> /CC @paskino ?

probably @paskino meant that currentl `BUILD_CIL=ON` is broken because of the above.

2024-01-08 22:09 UTC, casperdcl commented
i did ~a~ much thing.

~15min docker CI time (5min each for setup/build/test), or ~50min without `ccache`

Please check the updated PR description; hopefully it maketh sense @KrisThielemans @paskino :)

2024-01-10 08:53 UTC, KrisThielemans requested changes

2024-01-10 08:53 UTC, KrisThielemans commented on docker-compose.yml
> +  command: "bash -c 'cp -r /opt/ccache/* /ccache/'"
not sure why we copy? Can't we directly point ccache to /opt/ccache?

2024-01-10 08:53 UTC, KrisThielemans commented on docker-compose.yml
> +     -Dsiemens_to_ismrmrd_TAG=v1.2.11
this will have to go to version_config.cmake

2024-01-10 08:53 UTC, KrisThielemans commented on docker-compose.yml
> +     -Dsiemens_to_ismrmrd_TAG=v1.2.11
version_config.cmake

2024-01-10 08:53 UTC, KrisThielemans commented on docker-compose.yml
> +  user: ${USER_ID:-${UID:-${USER:-1000}}}
Just flagging as a concern.

I cannot quite remember all this, but we needed this for the mounting to work, but then it created trouble for file ownership/writeability (either in the container or in the host mounted dir), which we only found out when testing with a user that had a different UID/GID. So, we had to change ownership inside the container (which was difficult to do without having a large space or time penalty). Is this all sorted now?

2024-01-10 08:53 UTC, KrisThielemans commented on docker/.bashrc
> +[ -f PYTHON_INSTALL_DIR/bin/activate ] && export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:PYTHON_INSTALL_DIR/lib
I don't understand this. If `activate` exists, it should be called and it should take care of `LD_LIBRARY_PATH`, no?

2024-01-10 08:53 UTC, KrisThielemans commented on docker/compose.sh
> +test $build_cpu$build_gpu = 11 && regen_ccache=1
codacy will prefer lots of quotes around the expansions probably

2024-01-10 08:53 UTC, KrisThielemans commented on docker/compose.sh
> +export USER_ID UID
where would it get `USER_ID` from?

`GID` not necessary?

2024-01-10 08:53 UTC, KrisThielemans commented on docker/docker-compose.devel.yml
> +     -Dsiemens_to_ismrmrd_TAG=v1.2.11
a few more. I'll stop flagging them

2024-01-10 08:53 UTC, KrisThielemans commented on docker/start-gadgetron-notebook.sh
> +  test -d ${repo} || cp -dR "${SB_PATH}/../${repo}" .
now we have 2 copies, which is potentially confusing. Might be better to move? (but will run into user permissions probably). See also #816.

2024-01-10 08:53 UTC, KrisThielemans commented on docker/start-gadgetron-notebook.sh
> +pushd ~/work
Q: does ~/work always exist, even if not running via `docker/composesh`? (it won't be shared in the latter case)

2024-01-10 08:53 UTC, KrisThielemans commented on docker/start-gadgetron-notebook.sh
> +./SIRF-Exercises/scripts/download_data.sh
I'm a bit worried about this. This script has some options to specify locations (see also https://github.com/SyneRBI/SIRF-Exercises/pull/212 for better doc).
- I'm not sure what `start-gadgetron-notebook.sh` is called, but if someone set the directories by hand to a non-default location, will they be overwritten?
- On the STFC jupterhub image, the DOWNLOAD_DIR was on a shared location for all instances, to save bandwidth/space.

2024-01-10 08:53 UTC, KrisThielemans commented on docker/start-gadgetron-notebook.sh
> +  ln -s "${SIRF_INSTALL_PATH}/python/sirf/contrib" SIRF-contrib
linking here, but copying for the above. confusing.

2024-01-10 08:53 UTC, KrisThielemans commented on docker/start-gadgetron-notebook.sh
> +  --PasswordIdentityProvider.hashed_password='sha1:cbf03843d2bb:8729d2fbec60cacf6485758752789cd9989e756c' \
not so nice to have this here as hardwired, but I suppose this is fine.

2024-01-10 08:54 UTC, KrisThielemans commented
Could you clarify what the proposed situation is with the file ownership and permissions?

2024-01-10 14:06 UTC, casperdcl commented on Dockerfile
> +RUN echo "export OMP_NUM_THREADS=\$(python -c 'import multiprocessing as mc; print(mc.cpu_count() // 2)')" > /usr/local/bin/before-notebook.d/omp_num_threads.sh
idk; just doing what @paskino did.

NB both `nproc` and `multiprocessing.cpu_count()` yield logical processors rather than physical cores. The latter tends to be 2x less. I have no strong preference between the 3 options:

1. `//2`
2. `-1`
3. `//2 - 1`

2024-01-10 14:08 UTC, casperdcl commented on docker-compose.yml
> +  command: "bash -c 'cp -r /opt/ccache/* /ccache/'"
this is only a convenience function to copy `image@/opt/ccache` to `localhost@./docker/devel/.ccache`.

It's executed in `./docker/compose.sh` by `docker compose up sirf-build`.

2024-01-10 14:09 UTC, casperdcl commented on docker-compose.yml
> +     -Dsiemens_to_ismrmrd_TAG=v1.2.11
vis #851

2024-01-10 14:09 UTC, casperdcl commented on docker-compose.yml
> +     -Dsiemens_to_ismrmrd_TAG=v1.2.11
#851

2024-01-10 14:12 UTC, casperdcl commented on docker-compose.yml
> +  user: ${USER_ID:-${UID:-${USER:-1000}}}
it's all sorted but I need to document it. TL;DR: you need to run `export UID` before running docker.

2024-01-10 14:13 UTC, casperdcl commented on docker/.bashrc
> +[ -f PYTHON_INSTALL_DIR/bin/activate ] && export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:PYTHON_INSTALL_DIR/lib
prob meant to be:

```suggestion
[ -d PYTHON_INSTALL_DIR/lib ] && export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:PYTHON_INSTALL_DIR/lib
```

2024-01-10 14:14 UTC, casperdcl commented on docker/compose.sh
> +test $build_cpu$build_gpu = 11 && regen_ccache=1
I never put quotes around things guaranteed to have no spaces (or things where spaces are intentional, e.g. `$DCC_CPU`)

2024-01-10 14:18 UTC, casperdcl commented on docker/compose.sh
> +export USER_ID UID
- `USER_ID`: you could define this as a custom override
- `UID`: current user
- `GID`: not needed, vis. https://jupyter-docker-stacks.readthedocs.io/en/latest/using/common.html#user-related-configurations

2024-01-10 14:19 UTC, casperdcl commented on docker/start-gadgetron-notebook.sh
> +  test -d ${repo} || cp -dR "${SB_PATH}/../${repo}" .
idk; this is what the old images did as well (read-only repo in `/opt` is copied to user-writable workdir on container start)

2024-01-10 14:20 UTC, casperdcl commented on docker/start-gadgetron-notebook.sh
> +pushd ~/work
yes, it's all magically handled by the https://github.com/jupyter/docker-stacks base images

2024-01-10 14:22 UTC, casperdcl commented on docker/start-gadgetron-notebook.sh
> +  ln -s "${SIRF_INSTALL_PATH}/python/sirf/contrib" SIRF-contrib
because this is meant to be read-only rather than an editable demo

2024-01-18 10:00 UTC, casperdcl commented on docker/.bashrc
> +[ -f PYTHON_INSTALL_DIR/bin/activate ] && export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:PYTHON_INSTALL_DIR/lib
seems to be from https://github.com/SyneRBI/SIRF-SuperBuild/issues/573#issuecomment-862245695... maybe no longer needed>

2024-01-18 12:40 UTC, casperdcl commented on docker/.bashrc
> +[ -f PYTHON_INSTALL_DIR/bin/activate ] && export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:PYTHON_INSTALL_DIR/lib
removed

2024-02-15 12:50 UTC, KrisThielemans commented
#862 needs to be merged or rebased here before merge. Some work-arounds will then have to be removed.

2024-02-15 21:11 UTC, paskino commented on Dockerfile
> +RUN echo "export OMP_NUM_THREADS=\$(python -c 'import multiprocessing as mc; print(mc.cpu_count() // 2)')" > /usr/local/bin/before-notebook.d/omp_num_threads.sh
It's exactly to access the physical cores

2024-02-15 21:13 UTC, paskino commented
It looks good to be merged! @casperdcl @KrisThielemans

2024-02-15 22:33 UTC, KrisThielemans reviewed
A few final house-keeping tasks.

2024-02-15 22:33 UTC, KrisThielemans commented on .github/workflows/docker.yml
> +        # TODO: remove *_TAG after https://github.com/SyneRBI/SIRF-SuperBuild/issues/851
Obsolete comment?

2024-02-15 22:33 UTC, KrisThielemans commented on Dockerfile
> +RUN echo "export OMP_NUM_THREADS=\$(python -c 'import multiprocessing as mc; print(mc.cpu_count() // 2)')" > /usr/local/bin/before-notebook.d/omp_num_threads.sh
It's a wildly complicated way of getting this, but fine

2024-02-15 22:33 UTC, KrisThielemans commented on Dockerfile
> +RUN echo "export OMP_NUM_THREADS=\$(python -c 'import multiprocessing as mc; print(mc.cpu_count() // 2)')" > /usr/local/bin/before-notebook.d/omp_num_threads.sh
In fact, there is no good reason to restrict to number of physical cores. Looks like you don't believe in hyperthreading, but it works ok in my experience

2024-02-15 22:33 UTC, KrisThielemans commented on docker-compose.yml
> +     -Dsiemens_to_ismrmrd_TAG=v1.2.11
This needs to be removed now as versions have been updated

2024-02-15 22:33 UTC, KrisThielemans commented on docker-compose.yml
> +     -Dsiemens_to_ismrmrd_TAG=v1.2.11
Remove as well

2024-02-15 22:33 UTC, KrisThielemans commented on docker/docker-compose.devel.yml
> +     -Dsiemens_to_ismrmrd_TAG=v1.2.11
And this

2024-02-15 22:33 UTC, KrisThielemans commented on docker/requirements.yml
> +    # - proper fix: remove after https://github.com/TomographicImaging/CIL/issues/1600
Please create an issue for it such that we don't forget

2024-02-19 09:11 UTC, KrisThielemans commented
@paskino I think you requested my review. My comments were entered a few days ago. you should be able to see them via "unresolved conversations". Mostly: remove specific tags (as now all in version_config), possibly increase cores. Otherwise good to go.

2024-02-20 17:11 UTC, casperdcl commented on Dockerfile
> +RUN echo "export OMP_NUM_THREADS=\$(python -c 'import multiprocessing as mc; print(mc.cpu_count() // 2)')" > /usr/local/bin/before-notebook.d/omp_num_threads.sh
ok you can now `docker run ... -e OMP_NUM_THREADS=99` problems:

```suggestion
RUN echo 'test -z "$OMP_NUM_THREADS" && export OMP_NUM_THREADS=$(python -c "import multiprocessing as mc; print(mc.cpu_count() // 2)")' > /usr/local/bin/before-notebook.d/omp_num_threads.sh
```

2024-02-21 13:20 UTC, KrisThielemans approved these changes
I haven't tried this, nor looked at it in detail, but overall impression is good, and my remaining worries have been resolved, so let's merge!

2024-02-21 13:29 UTC, KrisThielemans commented
surely this must close quite a few more issues than what's listed?

2024-02-21 22:33 UTC, KrisThielemans commented
Major update indeed! Let's assign it to 3.6 and merge :-)

2024-02-21 22:36 UTC, merged