VM 3.3.0
SyneRBI/SIRF-SuperBuild pull request #755
Opened 2022-08-18 17:16 UTC by paskino

Creates the VM from the docker files.

Installs custom pip. 

closes #742

2022-08-18 19:15 UTC, KrisThielemans requested changes

2022-08-18 19:15 UTC, KrisThielemans commented on VirtualBox/scripts/INSTALL_prerequisites_with_apt-get.sh
> +# ${APT_GET_INSTALL} cython3 python3-h5py python3-wget
let's get rid of all these

2022-08-18 19:15 UTC, KrisThielemans commented on VirtualBox/scripts/INSTALL_python_packages.sh
> +${APT_GET_INSTALL} ${PYTHON}-dev
move to `INSTALL_...with_apt...`

2022-08-18 19:15 UTC, KrisThielemans commented on VirtualBox/scripts/INSTALL_python_packages.sh
> +# $PYTHON -m pip uninstall $PIPOPTIONS -y spyder-kernels
```suggestion
```

2022-08-18 19:15 UTC, KrisThielemans commented on VirtualBox/scripts/UPDATE.sh
>  PYTHON_EXECUTABLE=/usr/bin/python3
```suggestion
```

2022-08-18 19:17 UTC, KrisThielemans commented
so, did it work?

2022-08-18 19:58 UTC, KrisThielemans commented
doing most of these myself at the moment

2022-08-18 20:39 UTC, KrisThielemans commented
I'm going to squash-merge this now, and then fix some things later.

2022-08-18 20:45 UTC, merged

2022-08-19 06:11 UTC, paskino commented
> so, did it work?

Yes, it did! I opened the PR only after it all worked!

2022-08-19 08:57 UTC, KrisThielemans commented
great. I'm changing it anyway 😄 PR coming later today.