switch to jupyter lab
SyneRBI/SIRF-SuperBuild pull request #798
Opened 2023-01-20 16:26 UTC by paskino

closes #796

2023-01-20 17:12 UTC, KrisThielemans requested changes

2023-01-20 17:12 UTC, KrisThielemans commented on docker/service.sh
> +  jupyter lab --generate-config
I'm actually not 100% sure why we have this line, as it seems to generate a file with everything commented out anyway.

However, when using `jupyter lab --generate-config`, it generates a file ` /home/sirfuser/.jupyter/jupyter_lab_config.py`, so I think we need to repeat the `echo` line below for that file, such that it implies for both notebook and lab interface

2023-01-20 22:19 UTC, KrisThielemans requested changes
need to modify `Virtualbox/scripts/configure_jupyter.sh` as well. I have been trying but no success yet.

2023-01-20 23:17 UTC, paskino commented on docker/service.sh
> +  jupyter lab --generate-config
I don't know. I tried just to launch `jupyter lab` on the VM where I did not update this and I could log in with the normal password.

2023-01-20 23:20 UTC, paskino commented
> 

As before, I just issued `jupyter lab` instead of `jupyter notebook` and all worked fine without changing anything you are suggesting.

2023-01-21 09:30 UTC, KrisThielemans commented
The password setting is ignored. In fact, we need to create a different file
https://jupyter-server.readthedocs.io/en/stable/operators/migrate-from-nbserver.html

commits coming soon

2023-01-21 09:41 UTC, KrisThielemans commented
This should be ready now. I'll probably merge after check complete and trigger a Travis build, but feel free to find problems or merge yourself!

2023-01-21 09:47 UTC, KrisThielemans commented
hmmm, Doing a travis build uses ~4800 credits and we have 8500 left. Maybe I should save it for the release itself.

Can you do a local build of the "service" image and see if jupyter works?

2023-01-21 16:26 UTC, merged

2023-01-21 16:26 UTC, KrisThielemans commented
I've also get 25000 extra travis credits in the mean time. fast!