Update TomoPhantom and CCPi regularisation tags
SyneRBI/SIRF-SuperBuild pull request #813
Opened 2023-03-15 08:18 UTC by paskino

closes #812

2023-05-24 21:06 UTC, KrisThielemans commented
I've merged `master`. Possibly the tags are again already out-of-date of course.

2023-05-24 21:07 UTC, KrisThielemans requested changes
please update `CHANGES.md`

2023-05-25 07:14 UTC, KrisThielemans commented
CIL_regularisation tests failing with stuff like
```
  File "/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/CCPi-Regularisation-Toolkit/test/test_run_test.py", line 389, in test_TGV_CPU_vs_GPU
    (tgv_gpu, info_vec_gpu) = TGV(pars['input'],
  File "/home/runner/install/python/ccpi/filters/regularisers.py", line 117, in TGV
    return TGV_GPU(inputData,
NameError: name 'TGV_GPU' is not defined
```

2023-07-21 07:04 UTC, KrisThielemans commented on SuperBuild/External_CCPi-Regularisation-Toolkit.cmake
> +             COMMAND ${PYTHON_EXECUTABLE} -m unittest discover -s test -p test_CPU_*.py
can't we discover if there's a GPU (I think we have a CMake variable for it)? If not, then this is fine.

2023-09-11 16:02 UTC, paskino commented on SuperBuild/External_CCPi-Regularisation-Toolkit.cmake
> +             COMMAND ${PYTHON_EXECUTABLE} -m unittest discover -s test -p test_CPU_*.py
We have a variable `${${proj}_USE_CUDA}` but it only detects if CUDA SDK is present not the availability of a GPU.

2023-09-11 16:06 UTC, paskino commented on SuperBuild/External_CCPi-Regularisation-Toolkit.cmake
> +             COMMAND ${PYTHON_EXECUTABLE} -m unittest discover -s test -p test_CPU_*.py
At any rate this should be handled upstream, https://github.com/vais-ral/CCPi-Regularisation-Toolkit/issues/177

2023-09-11 21:36 UTC, KrisThielemans approved these changes
let's squash-merge this one. No idea why there are so many commits here!

2023-09-12 08:23 UTC, merged