CI: test docker CIL
SyneRBI/SIRF-SuperBuild pull request #838
Opened 2023-09-12 06:34 UTC by casperdcl

- follow-up to #837
- fixes https://github.com/SyneRBI/SIRF-SuperBuild/pull/835#issuecomment-1709896466
- part of #836

2023-09-12 06:58 UTC, casperdcl commented
@paskino I'm not sure this is actually required, since we now have `RUN_CTEST` https://github.com/SyneRBI/SIRF-SuperBuild/blob/c7b69730486e2c9e26d3654a5964631df3c5fb3d/docker/user_sirf-ubuntu.sh#L37

2023-09-12 07:14 UTC, KrisThielemans commented on .github/workflows/docker_build.yml
> +          curl -fsSL https://raw.githubusercontent.com/TomographicImaging/CIL/master/Wrappers/Python/test/test_SIRF.py > cil_sirf_test/test_SIRF.py
probably dangerous to use `master`?

2023-09-12 07:15 UTC, casperdcl commented on .github/workflows/docker_build.yml
> +          curl -fsSL https://raw.githubusercontent.com/TomographicImaging/CIL/master/Wrappers/Python/test/test_SIRF.py > cil_sirf_test/test_SIRF.py
```suggestion
          curl -fsSL https://raw.githubusercontent.com/TomographicImaging/CIL/0ba2f8e2935db66ec3dfe8c88e407e8d0eb5609f/Wrappers/Python/test/test_SIRF.py > cil_sirf_test/test_SIRF.py
```

2023-09-12 07:16 UTC, KrisThielemans commented on .github/workflows/docker_build.yml
> +          curl -fsSL https://raw.githubusercontent.com/TomographicImaging/CIL/master/Wrappers/Python/test/test_SIRF.py > cil_sirf_test/test_SIRF.py
Ideally get the hash from `version_config.cmake`

2023-09-12 07:20 UTC, casperdcl commented on .github/workflows/docker_build.yml
> +          curl -fsSL https://raw.githubusercontent.com/TomographicImaging/CIL/master/Wrappers/Python/test/test_SIRF.py > cil_sirf_test/test_SIRF.py
```suggestion
          DEFAULT_CIL_TAG=$(sed -nr 's/^\s*set\(DEFAULT_CIL_TAG (\w+)\)/\1/p' version_config.cmake)
          curl -fsSL https://raw.githubusercontent.com/TomographicImaging/CIL/$DEFAULT_CIL_TAG/Wrappers/Python/test/test_SIRF.py > cil_sirf_test/test_SIRF.py
```

2023-09-12 07:22 UTC, KrisThielemans commented on .github/workflows/docker_build.yml
> +          curl -fsSL https://raw.githubusercontent.com/TomographicImaging/CIL/master/Wrappers/Python/test/test_SIRF.py > cil_sirf_test/test_SIRF.py
I think CIL has a function to get the hash. @paskino will know

2023-09-12 08:33 UTC, paskino commented on .github/workflows/docker_build.yml
> +          curl -fsSL https://raw.githubusercontent.com/TomographicImaging/CIL/master/Wrappers/Python/test/test_SIRF.py > cil_sirf_test/test_SIRF.py
I think it is
```python 
from cil.version import commit_hash

print(commit_hash)

>>>g37cc671a
```

but it's not the long one.

2023-09-12 08:56 UTC, paskino submitted a review, later dismissed
I think it's very good. It picks the version from `version_config.cmake` and uses that.

2023-09-12 09:00 UTC, KrisThielemans commented
> I think it's very good. It picks the version from `version_config.cmake` and uses that.

but we're getting CIL via conda...

2023-09-12 15:42 UTC, casperdcl commented on .github/workflows/docker_build.yml
> +          docker run --rm -v cil_sirf_test:/cil_sirf_test -it synerbi/sirf:service python -m unittest discover /cil_sirf_test
```suggestion
          docker run --rm -v cil_sirf_test:/cil_sirf_test synerbi/sirf:service python -m unittest discover /cil_sirf_test
```

2023-09-12 20:27 UTC, KrisThielemans commented on .github/workflows/docker_build.yml
> +          curl -fsSL https://raw.githubusercontent.com/TomographicImaging/CIL/master/Wrappers/Python/test/test_SIRF.py > cil_sirf_test/test_SIRF.py
> though it seems raw.githubusercontent is fine with the short version too

phew!

This looks good to me. Only thing to add is some error checking on `DEFAULT_CIL_TAG` presumably. (If the `import cil` fails, the test needs to fail.

Also, I suppose I wouldn't call it `DEFAULT_CIL_TAG` anymore, but `CIL_HASH` or so.

2023-09-16 10:43 UTC, KrisThielemans commented
Error is
```
++ docker run --rm synerbi/sirf:service python -c 'import cil; print(cil.version.commit_hash[1:])'
error: exec: "python": executable file not found in $PATH
+ DEFAULT_CIL_TAG='Creating sirfuser:1000:1000
Adding user `sirfuser'\'' to group `users'\'' ...
Adding user sirfuser to group users
Done.
Updating file ownership for /home/sirfuser
Switching to sirfuser and executing python -c import cil; print(cil.version.commit_hash[1:])'
```
So, aside from not finding `python`, the `docker run` adds lots of other things to the output. I guess it could be avoided by doing a dummy `docker run` first, such that `sirfuser` is already created. Sigh

2023-09-17 19:46 UTC, casperdcl commented
btw how urgent is fixing this?

I was thinking of reworking/simplifing the docker stuff... but I expect it would take some time to get a more robust solution working.

2023-09-18 12:27 UTC, paskino commented
We would like to merge this in and then shortly [release SIRF 3.5.0](https://github.com/SyneRBI/SIRF/issues/1198) with relevant tested docker images.

2023-09-18 12:33 UTC, KrisThielemans commented
Or we don't merge it in, and test the docker images manually.

2023-09-20 08:39 UTC, KrisThielemans requested changes

2023-09-20 08:39 UTC, KrisThielemans commented on .github/workflows/docker_build.yml
> +          DEFAULT_CIL_TAG=$(docker run --rm synerbi/sirf:service /opt/conda/bin/python -c 'import cil; print(cil.version.commit_hash[1:])' | tail -n1)
rename to `CIL_TAG` or `CIL_HASH`

2023-09-20 08:39 UTC, KrisThielemans commented on .github/workflows/docker_build.yml
> +      - name: Test
```suggestion
      - name: Test CIL
```

2023-09-20 10:32 UTC, casperdcl commented on .github/workflows/docker_build.yml
> +          DEFAULT_CIL_TAG=$(docker run --rm synerbi/sirf:service /opt/conda/bin/python -c 'import cil; print(cil.version.commit_hash[1:])' | tail -n1)
I wanted to leave it as `DEFAULT_CIL_TAG` because that's what it's called in `version_config.cmake` (so it's easy to `grep` for all usages in future)... wdyt?

2023-09-20 10:51 UTC, KrisThielemans commented on .github/workflows/docker_build.yml
> +          DEFAULT_CIL_TAG=$(docker run --rm synerbi/sirf:service /opt/conda/bin/python -c 'import cil; print(cil.version.commit_hash[1:])' | tail -n1)
well, the reason for this fix is that it might be different from the `DEFAULT_CIL_TAG` if we install from `conda` (otherwise we could have simple used `version_config.cmake`)

2023-09-20 10:51 UTC, KrisThielemans commented on .github/workflows/docker_build.yml
> +          DEFAULT_CIL_TAG=$(docker run --rm synerbi/sirf:service /opt/conda/bin/python -c 'import cil; print(cil.version.commit_hash[1:])' | tail -n1)
put another way, it is the "actual" CIL Tag

2023-09-20 16:21 UTC, casperdcl commented
first problem: `cil.version` is borked. Hack for now:

```py
docker run --rm -it synerbi/sirf:service /opt/conda/bin/python
>>> import cil
>>> cil.version.version
'23.0.1'
>>> cil.version.commit_hash  # borked
'-1'
>>> f'v{cil.version.version}' if cil.version.commit_hash == '-1' else cil.version.commit_hash
'v23.0.1'
```

second problem: `sirf` isn't found

```py
docker run --rm -v ./cil_sirf_test:/cil_sirf_test synerbi/sirf:service /opt/conda/bin/python -m unittest discover -v /cil_sirf_test
...
----------------------------------------------------------------------
TEST SYSTEM CONFIGURATION
CIL version:  23.0.1
{'has_astra': True,
 'has_ccpi_regularisation': False,
 'has_cvxpy': False,
 'has_ipp': True,
 'has_numba': True,
 'has_nvidia': False,
 'has_tigre': True,
 'has_tomophantom': False}
----------------------------------------------------------------------

test_Gradient (test_SIRF.TestGradientMR_2D) ... skipped 'Skipping as SIRF is not available'
test_TVdenoisingMR (test_SIRF.TestGradientMR_2D) ... skipped 'Has SIRF'
test_Gradient (test_SIRF.TestGradientPET_2D) ... skipped 'Skipping as SIRF is not available'
test_Gradient (test_SIRF.TestGradientPET_3D) ... skipped 'Skipping as SIRF is not available'
test_BlockDataContainer_with_SIRF_DataContainer_add (test_SIRF.TestSIRFCILIntegration) ... skipped 'Has SIRF'
test_BlockDataContainer_with_SIRF_DataContainer_divide (test_SIRF.TestSIRFCILIntegration) ... skipped 'Has SIRF'
test_BlockDataContainer_with_SIRF_DataContainer_multiply (test_SIRF.TestSIRFCILIntegration) ... skipped 'Has SIRF'
test_BlockDataContainer_with_SIRF_DataContainer_subtract (test_SIRF.TestSIRFCILIntegration) ... skipped 'Has SIRF'

----------------------------------------------------------------------
Ran 8 tests in 0.000s

OK (skipped=8)
```

third problem: [`PYTHON_INSTALL_DIR` should be replaced with `/opt/conda`](https://github.com/SyneRBI/SIRF-SuperBuild/blob/4e270d582716a926bd88d30f52c123cd5cd2e4f5/docker/Dockerfile#L101) but for some reason isn't

```sh
docker run --rm synerbi/sirf:service cat .bashrc | grep activate
[ -f PYTHON_INSTALL_DIR/bin/activate ] && . PYTHON_INSTALL_DIR/bin/activate
```

hack for now:

```sh
docker run --rm -v ./cil_sirf_test:/cil_sirf_test synerbi/sirf:service bash --login -c '/opt/conda/bin/python -m unittest discover -v /cil_sirf_test'
```

fourth problem: gadgetron isn't running

```py
Started reading acquisitions from /opt/SIRF-SuperBuild/INSTALL/share/SIRF-3.5/data/examples/MR/simulated_MR_2D_cartesian.h5
0%..10%..20%..30%..40%..50%..60%..70%..80%..90%..100%..
Finished reading acquisitions from /opt/SIRF-SuperBuild/INSTALL/share/SIRF-3.5/data/examples/MR/simulated_MR_2D_cartesian.h5
connection to gadgetron server failed, trying again...
...
connection to gadgetron server failed
ERROR
...
----------------------------------------------------------------------
Ran 8 tests in 7.271s

FAILED (errors=6)
```

hack for now:

```sh
#file: ./cil_sirf_test/run.sh
this=$(dirname "${BASH_SOURCE[0]}")
$SIRF_PATH/../../INSTALL/bin/gadgetron >& ~/gadgetron.log&
/opt/conda/bin/python -m unittest discover -v $this
for i in $(jobs -p); do kill -n 15 $i; done 2>/dev/null
```

```sh
docker run --rm -v ./cil_sirf_test:/cil_sirf_test synerbi/sirf:service bash --login /cil_sirf_t
est/run.sh
```

fifth problem: `AttributeError: 'ImageData' object has no attribute 'get_item'`

```py
Started reading acquisitions from /opt/SIRF-SuperBuild/INSTALL/share/SIRF-3.5/data/examples/MR/simulated_MR_2D_cartesian.h5
0%..10%..20%..30%..40%..50%..60%..70%..80%..90%..100%..
Finished reading acquisitions from /opt/SIRF-SuperBuild/INSTALL/share/SIRF-3.5/data/examples/MR/simulated_MR_2D_cartesian.h5
Message received with ID: 5
Input stream has terminated
Message received with ID: 5
Input stream has terminated
WARNING:root:C backend is only for arrays of datatype float32 - defaulting to `numpy` backend
ok
test_TVdenoisingMR (test_SIRF.TestGradientMR_2D) ... Started reading acquisitions from /opt/SIRF-SuperBuild/INSTALL/share/SIRF-3.5/data/examples/MR/simulated_MR_2D_cartesian.h5
0%..10%..20%..30%..40%..50%..60%..70%..80%..90%..100%..
Finished reading acquisitions from /opt/SIRF-SuperBuild/INSTALL/share/SIRF-3.5/data/examples/MR/simulated_MR_2D_cartesian.h5
Message received with ID: 5
Input stream has terminated
Message received with ID: 5
Input stream has terminated
WARNING:root:C backend is only for arrays of datatype float32 - defaulting to `numpy` backend
...
WARNING:root:C backend is only for arrays of datatype float32 - defaulting to `numpy` backend
ok
test_Gradient (test_SIRF.TestGradientPET_2D) ... ok
test_Gradient (test_SIRF.TestGradientPET_3D) ... ok
test_BlockDataContainer_with_SIRF_DataContainer_add (test_SIRF.TestSIRFCILIntegration) ... ERROR
test_BlockDataContainer_with_SIRF_DataContainer_divide (test_SIRF.TestSIRFCILIntegration) ... ERROR
test_BlockDataContainer_with_SIRF_DataContainer_multiply (test_SIRF.TestSIRFCILIntegration) ... ERROR
test_BlockDataContainer_with_SIRF_DataContainer_subtract (test_SIRF.TestSIRFCILIntegration) ... ERROR

======================================================================
ERROR: test_BlockDataContainer_with_SIRF_DataContainer_add (test_SIRF.TestSIRFCILIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cil_sirf_test/test_SIRF.py", line 343, in test_BlockDataContainer_with_SIRF_DataContainer_add
    self.assertBlockDataContainerEqual(bdc , bdc1)
  File "/cil_sirf_test/testclass.py", line 40, in assertBlockDataContainerEqual
    self.assertBlockDataContainerEqual(container1.get_item(col),container2.get_item(col))
  File "/cil_sirf_test/testclass.py", line 34, in assertBlockDataContainerEqual
    if issubclass(container1.get_item(col).__class__, DataContainer):
AttributeError: 'ImageData' object has no attribute 'get_item'

======================================================================
ERROR: test_BlockDataContainer_with_SIRF_DataContainer_divide (test_SIRF.TestSIRFCILIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cil_sirf_test/test_SIRF.py", line 298, in test_BlockDataContainer_with_SIRF_DataContainer_divide
    self.assertBlockDataContainerEqual(bdc , bdc1)
  File "/cil_sirf_test/testclass.py", line 40, in assertBlockDataContainerEqual
    self.assertBlockDataContainerEqual(container1.get_item(col),container2.get_item(col))
  File "/cil_sirf_test/testclass.py", line 34, in assertBlockDataContainerEqual
    if issubclass(container1.get_item(col).__class__, DataContainer):
AttributeError: 'ImageData' object has no attribute 'get_item'

======================================================================
ERROR: test_BlockDataContainer_with_SIRF_DataContainer_multiply (test_SIRF.TestSIRFCILIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cil_sirf_test/test_SIRF.py", line 319, in test_BlockDataContainer_with_SIRF_DataContainer_multiply
    self.assertBlockDataContainerEqual(bdc , bdc1)
  File "/cil_sirf_test/testclass.py", line 40, in assertBlockDataContainerEqual
    self.assertBlockDataContainerEqual(container1.get_item(col),container2.get_item(col))
  File "/cil_sirf_test/testclass.py", line 34, in assertBlockDataContainerEqual
    if issubclass(container1.get_item(col).__class__, DataContainer):
AttributeError: 'ImageData' object has no attribute 'get_item'

======================================================================
ERROR: test_BlockDataContainer_with_SIRF_DataContainer_subtract (test_SIRF.TestSIRFCILIntegration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/cil_sirf_test/test_SIRF.py", line 363, in test_BlockDataContainer_with_SIRF_DataContainer_subtract
    self.assertBlockDataContainerEqual(bdc , bdc1)
  File "/cil_sirf_test/testclass.py", line 40, in assertBlock [...]

2023-09-21 08:41 UTC, paskino commented
The `get_item` problem has been fixed as of https://github.com/TomographicImaging/CIL/pull/1481 or better https://github.com/TomographicImaging/CIL/pull/1502 which means that the minimum commit of CIL that you can use is `0ba2f8e2935db66ec3dfe8c88e407e8d0eb5609f` which is exactly the hash that is in 
https://github.com/SyneRBI/SIRF-SuperBuild/blob/092f912fd76d36cd3995671809528db4c7cc1f33/version_config.cmake#L151

Notice that the bug is in `test_SIRF.py` rather than in CIL itself. This mess will disappear once we tag CIL.

2023-09-21 08:52 UTC, casperdcl commented
You mean the CIL version installed (`v23.0.1`) has nothing to do with the version specified in `version_config.cmake`? Then what's the point of the latter?

2023-09-21 08:55 UTC, KrisThielemans commented
Right, that'll be then because we get the `conda` version of CIL on `docker`. So, a few choices:
- give up on this test for 3.5
- set `BUILD_CIL=ON` and somehow prevent to install CIL via conda on top (i.e. don't use `SIRF-Exercises/environment.yml` at all, or edit it first.). This is an interesting problem in itself: if you build a package yourself, how do you prevent `conda` messing it up.
- make a CIL-dev conda version
- release a new version of CIL

which one do you prefer?

2023-09-21 08:58 UTC, KrisThielemans commented
> You mean the CIL version installed (`v23.0.1`) has nothing to do with the version specified in `version_config.cmake` (`0ba2f8e2`)? Then what's the point of the latter?

see 2nd bullet above. `version_config.cmake` is used when using the SB with `BUILD_CIL=ON`. Not when doing `conda install cil`

2023-09-21 13:23 UTC, paskino commented
> * give up on this test for 3.5
> * set `BUILD_CIL=ON` and somehow prevent to install CIL via conda on top (i.e. don't use `SIRF-Exercises/environment.yml` at all, or edit it first.). This is an interesting problem in itself: if you build a package yourself, how do you prevent `conda` messing it up.
> * make a CIL-dev conda version

This exists, the install command is about `conda install cil -c ccpi/label/dev`
> * release a new version of CIL

A new version of CIL should be out by the 27/9/23.

IMHO all this mess will go away once we tag and release CIL, so I suggest to wait until then.

2023-09-21 14:05 UTC, KrisThielemans commented
ok. Of course, we will have the same problem later. I think what this is saying (no surprise): either use `conda` or use the `SuperBuild`, but don't try to mix.

2023-09-22 13:20 UTC, casperdcl commented
long (cough, mid)-term solution would be `pyproject.toml` + https://github.com/scikit-build/scikit-build/ à la https://github.com/AMYPAD/CuVec - no need for SuperBuild or conda at all 😈

2023-09-22 13:59 UTC, KrisThielemans commented
I have no idea really, but looks interesting.

We started with the SB because lots of things were not available on various systems (Gadgetron, ISMRMD, STIR, ...). That is less and less the case (although most of these are on conda only). Another reason was to have tight version control. I'm not sure how scikit-build would resolve external dependencies. 

I'm happy to go with whatever makes our life easier (but serves the needs).

This needs a serious discussion of course.

2023-09-27 19:06 UTC, casperdcl commented
fyi this PR is blocked on https://github.com/TomographicImaging/CIL/issues/1509 :)

2023-09-27 19:25 UTC, KrisThielemans commented
that' s a long checklist!

2023-10-02 18:35 UTC, casperdcl commented
post CIL 23.1.0 release, we still have [one error](https://github.com/SyneRBI/SIRF-SuperBuild/actions/runs/6251726661/job/17314661344?pr=838)

2023-10-02 19:56 UTC, KrisThielemans commented
for easy reference
```
ERROR: test_TVdenoisingMR (test_SIRF.TestGradientMR_2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sirfuser/cil_sirf_test/test_SIRF.py", line 255, in test_TVdenoisingMR
    res1 = TV.proximal(self.image1, tau=1.0)
  File "/opt/conda/lib/python3.10/site-packages/cil/optimisation/functions/TotalVariation.py", line 271, in proximal
    solution = self._fista_on_dual_rof(x, tau)
  File "/opt/conda/lib/python3.10/site-packages/cil/optimisation/functions/TotalVariation.py", line 303, in _fista_on_dual_rof
    p1 = self.gradient.range_geometry().allocate(None)
  File "/opt/conda/lib/python3.10/site-packages/cil/framework/BlockGeometry.py", line 56, in allocate
    containers = [geom.allocate(value, **kwargs) for geom in self.geometries]
  File "/opt/conda/lib/python3.10/site-packages/cil/framework/BlockGeometry.py", line 56, in <listcomp>
    containers = [geom.allocate(value, **kwargs) for geom in self.geometries]
  File "/opt/SIRF-SuperBuild/INSTALL/python/sirf/Gadgetron.py", line 526, in allocate
    tmp = value * numpy.ones(out.as_array().shape)
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```
Relevant lines are https://github.com/SyneRBI/SIRF/blob/d3956345ec6e56421017a6aca34c73747dbae664/src/xGadgetron/pGadgetron/Gadgetron.py#L508-L527
Indeed, the argument `None` is not supported by `Gadgetron.ImageData.allocate`. I've created https://github.com/SyneRBI/SIRF/issues/1212.

Do we need this for `AcquisitionData` as well?

This seems to need a SIRF update then... (which means branching off from 3.5 to release 3.5.1).

2023-10-03 15:56 UTC, paskino commented
> This seems to need a SIRF update then... (which means branching off from 3.5 to release 3.5.1).

Let's then proceed with tagging the SB with 3.5 without this PR and tackle this later.

2023-10-03 16:33 UTC, KrisThielemans commented
> Let's then proceed with tagging the SB with 3.5 without this PR and tackle this later.

I don't know... I guess you'd want the freshly released CIL in our `version_config.cmake`. That'd presumably make GHA fail (or at least, I'd hope it would. TBH, I don't understand why it didn't, unless the current CIL tag didn't include that test).

We could leave the CIL version as-is and then release 3.5.1 soon after which would presumably
- use SIRF 3.5.1 with fixing the above
- use CIL from today
- switch `BUILD_CIL=ON` in docker, and remove using the SIRF- exercises `environment.yml`.

In any case, these steps seems minor (aside from probably the last one...) and need to be completed ASAP. If they are indeed minor, then releasing 3.5.0 as-is might be double work. Up to you.

2023-10-03 16:35 UTC, KrisThielemans commented
Of course, there are 2 issues on our milestone list that do need to be resolved. https://github.com/SyneRBI/SIRF-SuperBuild/milestone/14

2023-10-11 20:01 UTC, casperdcl commented
ok so

- merged #840 into here (bumping CIL to 23.1.0)
- [skipped the failing test](https://github.com/SyneRBI/SIRF-SuperBuild/pull/838/commits/efbdfb94ec25554d5fd65e992ae3b54b77962fdb)

should be gewd for SIRF 3.5.0?

2023-10-13 09:51 UTC, merged