update CIL and CCPi-Regularisation version and reinstate tests
SyneRBI/SIRF-SuperBuild pull request #897
Opened 2024-05-13 17:34 UTC by paskino

Bump CIL and CCPi-Regularisation-Toolkit versions for PSMR24 training school

- closes #832

2024-05-13 22:13 UTC, KrisThielemans reviewed
Is there anything here for me to check? 

Obviously, merge the SIRF PR first and set SIRF_TAG accordingly

2024-05-14 06:12 UTC, paskino commented
@KrisThielemans do you have any clue onto why ROOT fails to build with these changes?

2024-05-14 08:07 UTC, KrisThielemans commented
https://github.com/SyneRBI/SIRF-SuperBuild/actions/runs/9074911667/job/24934505517?pr=897#step:10:10217
```
[  0%] Performing install step for 'XROOTD'
CMake Error at /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ROOT/build/builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-install-Release.cmake:49 (message):
  Command failed: 1
   '/usr/local/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ROOT/build/builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-install-Release-impl.cmake'
  See also
    /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ROOT/build/builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-install-*.log
```
Luckily, we do upload logs as an artefact (visible in the Summary of the Action). Checking the install-err.log:
``
gmake[7]: *** read jobs pipe: Bad file descriptor.  Stop.
gmake[7]: *** Waiting for unfinished jobs....
gmake[6]: *** [Makefile:136: all] Error 2
```
We have had this before https://github.com/root-project/root/issues/14520 and it auto-disappeared.

Presumably our build is overload the MS network... Sadly, I'm not sure what can be done about it. I suppose we could modify the job to use a packaged ROOT as opposed to building it ourselves, and have one that does build it, but is allowed to fail.

2024-05-14 09:49 UTC, KrisThielemans commented
Here's what we do in STIR GHA
https://github.com/UCL/STIR/blob/feb6d85eadb392f5b8278d3b97ae2ee67ca439d9/.github/workflows/build-test.yml#L260-L264
You'd then have to say `USE_SYSTEM_ROOT=ON`. Of course, it would make sense to put the download in the docker scripts. Not 100% sure about the `source .../thisroot.sh` though.

2024-05-14 11:25 UTC, paskino commented
Does this mean we will not test `BUILD_ROOT=ON` rather `USE_SYSTEM_ROOT=ON` on the CI?

2024-05-14 12:06 UTC, KrisThielemans commented
yes, I think it'd be nice to have one job where we build it ourselves, but allow failure, as I wrote.

2024-05-15 16:08 UTC, casperdcl requested changes

2024-05-15 16:08 UTC, casperdcl commented on Dockerfile
> +RUN BUILD_CIL="${BUILD_CIL}" bash /opt/scripts/user_demos.sh \
`BUILD_CIL` isn't available here as it's a different stage (`FROM`) in teh Dockerfile

```suggestion
RUN bash /opt/scripts/user_demos.sh \
```

2024-05-15 16:08 UTC, casperdcl commented on docker/user_demos.sh
> +    if test "${BUILD_CIL:-0}" != 0; then
```suggestion
    # do not install CIL from conda if SuperBuild already built it
    if test "$(conda list '^cil$')" != "[]"; then
```

2024-05-15 16:12 UTC, casperdcl commented on docker/user_demos.sh
> +    conda env update --file environment-sirf.yml -v
up to you if this is needed, idk.

```suggestion
    conda env update --file environment-sirf.yml
```

2024-05-15 16:12 UTC, casperdcl commented on version_config.cmake
> +set(DEFAULT_CCPi-Regularisation-Toolkit_TAG "fix_3D_regularisers") # fix_
incomplete `# comment` here?

2024-05-15 16:23 UTC, casperdcl commented on docker/user_demos.sh
> +    if test "$(conda list '^cil$')" != "[]"; then
mea culpa

```suggestion
    if test "$(conda list '^cil$' --json)" != "[]"; then
```

2024-05-16 10:37 UTC, casperdcl requested changes
fix bugs

2024-05-16 10:37 UTC, casperdcl commented on Dockerfile
> + && if test "$BUILD_CIL" != 0; then \
```suggestion
 && if test "$BUILD_CIL" != "OFF"; then \
```

2024-05-16 10:37 UTC, casperdcl commented on docker/user_demos.sh
> +    if test "${BUILD_CIL:-0}" != 0; then
```suggestion
    if test "${BUILD_CIL:-OFF}" != "OFF"; then
```

2024-05-16 17:44 UTC, KrisThielemans commented
Please merge `master` to get the correct STIR version.

2024-05-31 04:56 UTC, KrisThielemans commented
@paskino @casperdcl this is ready to merge from my perspective. Please ahead, and then tag.

2024-05-31 10:34 UTC, casperdcl commented
IIRC @paskino found another bug

2024-05-31 10:44 UTC, casperdcl commented on Dockerfile
> +COPY --from=build --link --chown=${NB_USER} /opt/SIRF-SuperBuild/INSTALL/bin/env_sirf.sh /opt/conda/etc/conda/activate.d
I'm not sure this is ideal...

- server overrides `$HOME`: ok
- server doesn't override `$HOME`: `env_sirf.sh` gets sourced twice (once by `$HOME/.bashrc`, once by `conda/activate.d/*`)

Perhaps we should change `env_sirf.sh` to do nothing if it's already been sourced once?

```sh
test -n "$SIRF_ENV_SOURCED" && exit 0; SIRF_ENV_SOURCED=1; # pragma once
```

2024-05-31 10:49 UTC, casperdcl commented on Dockerfile
> +COPY --from=build --link --chown=${NB_USER} /opt/SIRF-SuperBuild/INSTALL/bin/env_sirf.sh /opt/conda/etc/conda/activate.d
added to da65e19

2024-05-31 11:53 UTC, KrisThielemans commented on env_sirf.sh.in
> +test -n "$SIRF_ENV_SOURCED" && return; SIRF_ENV_SOURCED=1 # pragma once
this is problematic outside docker/jupyterhub. Some of us have different versions of the SB and switch between them by sourcing different .sh files. This would no longer work.

Of course, it'd be better if the script wouldn't append/prepend to `PATH` etc if it's already the latest. Checking if `env_sirf.sh` is in the PATH and if so, it's in `@SyneRBI_INSTALL@/bin could help, but it doesn't seem to be so easy to do.

Why is it a problem?

2024-05-31 17:20 UTC, casperdcl commented on env_sirf.sh.in
> +test -n "$SIRF_ENV_SOURCED" && return; SIRF_ENV_SOURCED=1 # pragma once
Ah I see makes sense.

Probably best to revert and put up with `PATH` cruft

2024-05-31 18:44 UTC, KrisThielemans commented on env_sirf.sh.in
> +test -n "$SIRF_ENV_SOURCED" && return; SIRF_ENV_SOURCED=1 # pragma once
yes please. we can always fix that later (TM)

2024-06-03 14:49 UTC, casperdcl commented on env_sirf.sh.in
> +test -n "$SIRF_ENV_SOURCED" && return; SIRF_ENV_SOURCED=1 # pragma once
```suggestion
```

2024-06-06 08:42 UTC, paskino commented on version_config.cmake
> +set(DEFAULT_CIL_TAG 501726d8f09c16faef19ceb69b85c212db2eeca6) # 16 May 2024
```suggestion
set(DEFAULT_CIL_TAG ccf17f393ba911d13b74f2327779dde030098fe6) # 16 May 2024
```

2024-06-06 08:43 UTC, paskino commented on version_config.cmake
> +set(DEFAULT_CIL_TAG 501726d8f09c16faef19ceb69b85c212db2eeca6) # 16 May 2024
```suggestion
set(DEFAULT_CIL_TAG ccf17f393ba911d13b74f2327779dde030098fe6) # 28 May 2024
```

2024-06-06 08:44 UTC, paskino commented
waiting for 
- https://github.com/TomographicImaging/CCPi-Regularisation-Toolkit/pull/205
Then update the tag for the CCPi-Regularisation in the `version_config.cmake` and merge

2024-06-06 09:17 UTC, casperdcl requested changes
I merged https://github.com/TomographicImaging/CCPi-Regularisation-Toolkit/pull/205 and released it as `v24.0.1`... I presume ~you manually~ jenkins will upload it to `conda -c ccpi`

2024-06-06 09:17 UTC, casperdcl commented on CHANGES.md
> +  - CCPi-Regularisation-Toolkit: fix_3D_regularisers branch
```suggestion
  - CCPi-Regularisation-Toolkit: v24.0.1
```

2024-06-06 09:17 UTC, casperdcl commented on version_config.cmake
> +set(DEFAULT_CCPi-Regularisation-Toolkit_TAG "fix_3D_regularisers")
```suggestion
set(DEFAULT_CCPi-Regularisation-Toolkit_TAG "v24.0.1")
```

2024-06-07 13:19 UTC, KrisThielemans requested changes
tiny change. then merge!

2024-06-07 13:28 UTC, casperdcl commented on Dockerfile
> +RUN echo 'test -z "$OMP_NUM_THREADS" && export OMP_NUM_THREADS=$(python -c "import multiprocessing as mc; print(mc.cpu_count() - 2)")' > /usr/local/bin/before-notebook.d/omp_num_threads.sh
```suggestion
RUN echo 'test -z "$OMP_NUM_THREADS" && export OMP_NUM_THREADS=$(python -c "import multiprocessing as mc; print(max(1, mc.cpu_count() - 2))")' > /usr/local/bin/before-notebook.d/omp_num_threads.sh
```

2024-06-09 03:27 UTC, KrisThielemans commented
@casperdcl @paskino please merge and tag

2024-06-10 08:29 UTC, casperdcl requested changes

2024-06-10 08:29 UTC, casperdcl commented on docker/user_demos.sh
> +      sed -r -i -e '/^\s*- (cil).*/d' environment-sirf.yml
Isn't this better now @paskino ?
```suggestion
      sed -r -i -e '/# cil/d' environment-sirf.yml
```

2024-06-10 08:29 UTC, casperdcl commented on CHANGES.md
> +  - CIL: 501726d8f09c16faef19ceb69b85c212db2eeca6 # 16 May 2024
```suggestion
  - CIL: ccf17f393ba911d13b74f2327779dde030098fe6 # 28 May 2024
```

2024-06-10 08:37 UTC, casperdcl commented on docker/user_demos.sh
> +      sed -r -i -e '/^\s*- (cil).*/d' environment-sirf.yml
Oh actually it applies to https://github.com/SyneRBI/SIRF-Exercises/blob/master/environment.yml, in wguch case there's no `cil-data`, right?

2024-06-10 10:16 UTC, casperdcl commented
Still some failing tests @paskino ...

gcc-9:

```py
======================================================================
ERROR: test_TVdenoisingMR (test_SIRF.TestGradientMR_2D)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/CIL/Wrappers/Python/test/test_SIRF.py", line 263, in test_TVdenoisingMR
    fista.run(verbose=0)
  File "/home/runner/install/python/cil/optimisation/algorithms/Algorithm.py", line 240, in run
    for _ in zip(range(self.iteration, self.iteration + iterations), self):
  File "/home/runner/install/python/cil/optimisation/algorithms/Algorithm.py", line 108, in __next__
    self.update()
  File "/home/runner/install/python/cil/optimisation/algorithms/FISTA.py", line 295, in update
    self.f.gradient(self.y, out=self.x)
  File "/home/runner/install/python/cil/optimisation/functions/Function.py", line 480, in gradient
    res *= self.scalar
TypeError: unsupported operand type(s) for *=: 'NoneType' and 'float'
----------------------------------------------------------------------

======================================================================
ERROR: test_CPU_regularisers (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_CPU_regularisers
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/sources/CCPi-Regularisation-Toolkit/test/test_CPU_regularisers.py", line 6, in <module>
    from ccpi.filters.regularisers import FGP_TV, SB_TV, TGV, LLT_ROF, FGP_dTV, NDF, Diff4th, ROF_TV, PD_TV
Errors while running CTest
ModuleNotFoundError: No module named 'ccpi'
```

gcc-11:

```
-- XROOTD build command succeeded.  See also /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ROOT/build/builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-build-*.log
[  0%] Performing install step for 'XROOTD'
CMake Error at /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ROOT/build/builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-install-Release.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ROOT/build/builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-install-Release-impl.cmake'

  See also

    /home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/ROOT/build/builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-install-*.log

gmake[5]: *** [builtins/xrootd/CMakeFiles/XROOTD.dir/build.make:104: builtins/xrootd/XROOTD-prefix/src/XROOTD-stamp/XROOTD-install] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:9131: builtins/xrootd/CMakeFiles/XROOTD.dir/all] Error 2
gmake[3]: *** [Makefile:156: all] Error 2
gmake[2]: *** [CMakeFiles/ROOT.dir/build.make:86: builds/ROOT/stamp/ROOT-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:590: CMakeFiles/ROOT.dir/all] Error 2
```

2024-06-10 12:12 UTC, merged