attempt to use system ROOT
SyneRBI/SIRF-SuperBuild pull request #901
Opened 2024-05-16 13:57 UTC by KrisThielemans

Alternative to #898 

Fixes #899

2024-05-16 14:01 UTC, KrisThielemans commented
@casperdcl the actions don't run. Presumably I have an error in the yml file, but I forgot how to find out. Can you help?

2024-05-16 15:05 UTC, KrisThielemans commented
ok. well. I fixed the syntax, but now by condition doesn't work. I need help...

2024-05-17 08:04 UTC, casperdcl requested changes

2024-05-17 08:04 UTC, casperdcl commented on .github/workflows/c-cpp.yml
> +    - if: contains(matrix.EXTRA_BUILD_FLAGS, fromJSON('["USE_SYSTEM_ROOT=ON"]'))
```suggestion
    - if: contains(matrix.EXTRA_BUILD_FLAGS, "-DUSE_SYSTEM_ROOT=ON"))
```

2024-05-17 08:04 UTC, casperdcl commented on .github/workflows/c-cpp.yml
> +        source root/bin/thisroot.sh
Does this install to system binary dirs, or merely append to PATH?

2024-05-17 08:45 UTC, KrisThielemans commented on .github/workflows/c-cpp.yml
> +        source root/bin/thisroot.sh
That gives me
```
[Invalid workflow file: .github/workflows/c-cpp.yml#L85](https://github.com/SyneRBI/SIRF-SuperBuild/actions/runs/9125488514/workflow)
The workflow is not valid. .github/workflows/c-cpp.yml (Line: 85, Col: 11): Unexpected symbol: '"-DUSE_SYSTEM_ROOT'. Located at position 36 within expression: contains(matrix.EXTRA_BUILD_FLAGS, "-DUSE_SYSTEM_ROOT=ON"))
```

2024-05-17 08:45 UTC, KrisThielemans commented on .github/workflows/c-cpp.yml
> +    - if: contains(matrix.EXTRA_BUILD_FLAGS, fromJSON('["USE_SYSTEM_ROOT=ON"]'))
[Invalid workflow file: .github/workflows/c-cpp.yml#L85](https://github.com/SyneRBI/SIRF-SuperBuild/actions/runs/9125488514/workflow)
The workflow is not valid. .github/workflows/c-cpp.yml (Line: 85, Col: 11): Unexpected symbol: '"-DUSE_SYSTEM_ROOT'. Located at position 36 within expression: contains(matrix.EXTRA_BUILD_FLAGS, "-DUSE_SYSTEM_ROOT=ON"))

2024-05-31 00:15 UTC, KrisThielemans commented on .github/workflows/c-cpp.yml
> +        source root/bin/thisroot.sh
added them all to GITHUB_ENV

2024-05-31 00:15 UTC, KrisThielemans commented on .github/workflows/c-cpp.yml
> +    - if: contains(matrix.EXTRA_BUILD_FLAGS, fromJSON('["USE_SYSTEM_ROOT=ON"]'))
I gave up on this and just did it in bash. Feel free to fix at some point!

2024-05-31 00:19 UTC, merged