docker: use CMake 3.29.6
SyneRBI/SIRF-SuperBuild pull request #917
Opened 2024-07-01 21:40 UTC by KrisThielemans

2024-07-01 21:55 UTC, casperdcl requested changes

2024-07-01 21:55 UTC, casperdcl commented on docker/build_essential-ubuntu.sh
> +export PATH="$PWD/cmake/bin:$PATH"
This won't persist for subsequent steps.

Perhaps untar into `/usr/local/bin` instead?

2024-07-01 22:24 UTC, KrisThielemans commented on docker/build_essential-ubuntu.sh
> +export PATH="$PWD/cmake/bin:$PATH"
ah well. It used to work, but I believe you. Not sure if that link will be sufficient.

Of course, we also have https://github.com/SyneRBI/SIRF-SuperBuild/blob/d725d08f3d18308f4f14ab1b249e70b2acdbdc67/VirtualBox/scripts/INSTALL_CMake.sh

2024-07-02 06:45 UTC, casperdcl commented on docker/build_essential-ubuntu.sh
> +tar xzf cmake.tgz && rm cmake.tgz
```suggestion
mkdir -p /usr/local
pushd /usr/local
tar xzf $INSTALL_DIR/cmake.tgz --strip 1
popd
rm cmake.tgz
```

2024-07-02 08:44 UTC, paskino commented on SuperBuild/External_Gadgetron.cmake
> +  # TODO enable it once bug fixed
I got a different bug though!

```
34 errors detected in the compilation of "/opt/SIRF-SuperBuild/sources/Gadgetron/toolboxes/nfft/gpu/cuGriddingConvolution.cu".```

2024-07-02 08:46 UTC, paskino commented on SuperBuild/External_Gadgetron.cmake
> +  # TODO enable it once bug fixed
Possibly it is better to refer to
- https://github.com/SyneRBI/SIRF-SuperBuild/issues/619

2024-07-02 09:45 UTC, merged