Updated modules in find_package command for Python3
SyneRBI/SIRF-SuperBuild pull request #933
Opened 2024-10-02 16:40 UTC by NicoleJurjew

2024-10-03 08:35 UTC, KrisThielemans commented
https://cmake.org/cmake/help/latest/module/FindPythonInterp.html deprecated since 3.12, while we require 3.16.2.

Current change is minimal. We probably should pass `Python_EXECUTABLE` as opposed to `PYTHON_EXECUTABLE` to dependencies, but this needs a check which ones we use. Probably easiest to pass both. I think we should no longer attempt to pass include and other paths, and let CMake sort it out.

2024-10-03 08:36 UTC, KrisThielemans commented on SuperBuild.cmake
> +  find_package(CUDAToolkit REQUIRED)
```suggestion
  find_package(CUDA)
```
While this is needed, let's do it in another PR, as both of these could create discussions.

2024-10-03 08:37 UTC, KrisThielemans commented on SuperBuild.cmake
> +  set (BUILD_PYTHON = ${Python3_FOUND})
```suggestion
  set (BUILD_PYTHON ${Python3_FOUND})
```

2024-10-03 09:54 UTC, KrisThielemans commented
Need to update how we look for cython I guess
```
[100%] Generating build/timestamp
Traceback (most recent call last):
  File "/home/runner/work/SIRF-SuperBuild/SIRF-SuperBuild/build/builds/TomoPhantom/build/Wrappers/Python/setup.py", line 19, in <module>
    from Cython.Distutils import build_ext
ModuleNotFoundError: No module named 'Cython'
gmake[5]: *** [Wrappers/Python/CMakeFiles/PythonWrapper.dir/build.make:76: Wrappers/Python/build/timestamp] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:157: Wrappers/Python/CMakeFiles/PythonWrapper.dir/all] Error 2
gmake[3]: *** [Makefile:136: all] Error 2
gmake[2]: *** [CMakeFiles/TomoPhantom.dir/build.make:86: builds/TomoPhantom/stamp/TomoPhantom-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:755: CMakeFiles/TomoPhantom.dir/all] Error 2
```
This error is different from why I saw in  #932 but it's possible that @NicoleJurjew only saw the Tomophantom error when using this branch I guess.

2024-10-04 09:13 UTC, KrisThielemans commented
that's a bit strange. What is the content of env_sirf.sh etc then? Can you just do a
```cmake
message(STATUS "PYTHON_EXECUTABLE=${PYTHON_EXECUTABLE}")
```
before those statement to check what it is?

2024-10-04 10:51 UTC, NicoleJurjew commented
This is the content of env_sirf.sh:
![grafik](https://github.com/user-attachments/assets/772d4f8d-da24-43dc-afed-cdcb960a8cd4)

Where will that message be written to then? Thanks!

2025-02-13 10:24 UTC, paskino commented
See also #313

2025-03-20 14:31 UTC, casperdcl commented
Looks  like a gadgetron build error related to https://groups.google.com/g/linux.debian.bugs.dist/c/JpHAw3GY0Bk

2025-03-20 15:12 UTC, KrisThielemans commented
This was all discussed in #937. I've contributed a PR to Gadgetron. However, moving on with Gadgetron created a lot of other problems. So @paskino and I decided to wait with that, and just fix Ubuntu 22.04. This is done in #943. So suggestion therefore is to finish #943, merge it, and merge that back on here.

2025-03-20 15:23 UTC, KrisThielemans reviewed
Did you check if the dependencies indeed accept `Python3_EXECUTABLE`. In any case, I'm fairly sure this needs to be `Python_EXECUTABLE`. Easiest might be to pass both of course, although that's a bit ugly.

Also, in SIRF and STIR, we have a "backwards compatible" line to set `Python_EXECUTABLE` if `PYTHON_EXECUTABLE` is set. Maybe no longer need it?

2025-03-21 09:45 UTC, KrisThielemans commented
@casperdcl I've merged #943.

Note that we'll also need to update CHANGES.md here.

2025-03-21 10:23 UTC, casperdcl commented on SuperBuild.cmake
technically

`find_package` | `-D` hint
--|--
`Python3` | `Python3_EXECUTABLE`
`Python` | `Python_EXECUTABLE`

so perhaps we could just use `Python` without the `3`-suffix everywhere?

2025-03-21 12:01 UTC, KrisThielemans requested changes

2025-03-21 12:01 UTC, KrisThielemans commented on SuperBuild.cmake
>    if (PYTHONLIBS_FOUND)
Python_*, and different conditional

2025-03-21 12:01 UTC, KrisThielemans commented on SuperBuild.cmake
>    if (EXISTS "${PYTHON_INCLUDE_DIR}")
Python, not PYTHON

2025-03-21 12:09 UTC, casperdcl commented on SuperBuild/External_NiftyPET.cmake
> +      -DPython3_Executable=${NiftyPET_PYTHON_EXECUTABLE}
Any reason why? Current NiftyPET is Python3 only.

2025-03-21 12:19 UTC, KrisThielemans commented
There seem to be 2 different Python versions used in the CIL install, resulting in the `cil` not being found at import. There are 2 causes for this.

For the SB, CMake finds a surprising version (which is then passed on)
```
Found Python: /opt/hostedtoolcache/Python/3.10.12/x64/bin/python3.10 (found version "3.10.12") found components: Interpreter Development Development.Module Development.Embed
Found Python_EXECUTABLE=/opt/hostedtoolcache/Python/3.10.12/x64/bin/python3.10
```
The CMake strategy for selecting a python version is still far too complicated/error-prone. I suggest therefore to explicitly set
`Python_EXECUTABLE=`which python` in the Action.

In addition, it looks like the CIL version that is being built (I only checked with `DEVEL_BUILD=OFF`) uses old-style:
```
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.10.so (found version "3.10.12")
-- Found PYTHON_EXECUTABLE=/home/runner/virtualenv/bin/python
```
I think therefore we need to add `PYTHON_EXECUTABLE` to the `PYTHONLIBS_CMAKE_ARGS` variable. That's safest in any case.

2025-03-21 12:20 UTC, KrisThielemans commented on VirtualBox/scripts/UPDATE_functions.sh
> +        -DPython3_EXECUTABLE="$PYTHON_EXECUTABLE"\
oh, right. This is on the VM. Sorry. Let's leave this in then.

2025-03-21 12:21 UTC, KrisThielemans commented on VirtualBox/scripts/UPDATE_functions.sh
> +        -DPython3_EXECUTABLE="$PYTHON_EXECUTABLE"\
Certainly as on GHA, CMake found the wrong python...

2025-03-21 12:25 UTC, KrisThielemans commented on SuperBuild/External_NiftyPET.cmake
> +      -DPython3_Executable=${NiftyPET_PYTHON_EXECUTABLE}
We currently only use NiftyPET via STIR, but that all happens on the C++ front. NiftyPET3 no longer has the appropriate libraries, and I have no energy for it.

See https://github.com/UCL/STIR/issues/1294 to jog your mind :-)

2025-03-21 18:03 UTC, KrisThielemans commented
```
ModuleNotFoundError: No module named 'Cython'
```
when building TomoPhantom. Not sure why this happens now? Wrong python used? TBH, We shouldn't really build TomoPhantom as part of our CI I think. @paskino ?

```
Run actions/upload-artifact@v4
  with:
    name: build_log_files-ubuntu-22.04-gcc9-Release-DEVEL=OFF
...
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
I guess we have a problem with the naming somewhere.

2025-03-24 12:48 UTC, casperdcl commented
`TomoPhantom` `v2.0.0` (and also the slightly more recent `v3.0`) doesn't specify build deps. Its `setup.py` needs `Cython` & `numpy`. Adding them to the build step works.

Current test failures due to lack of CIL deps.

[CIL:scripts/requirements-test.yml](https://github.com/TomographicImaging/CIL/blob/master/scripts/requirements-test.yml) are not included in [CIL:pyproject.toml](https://github.com/TomographicImaging/CIL/blob/master/pyproject.toml) and I think they should be.

2025-03-24 16:05 UTC, KrisThielemans commented on SuperBuild.cmake
> +  if (Python_Development_FOUND)
we require it, so no extra `if`

2025-03-24 16:05 UTC, KrisThielemans commented on SuperBuild.cmake
> +      -DPYTHON_LIBRARY=${Python_LIBRARIES})
I don't think we should be setting the `*DIRS` and `*LIBRARIES` variables, only the "singular" ones, as they are the input ones, while the "plural" variables are the output. (It could go wrong when there are multiple directories in the "plural" variables).

That means though that we should only set those if the input ones are set.

2025-03-24 18:33 UTC, KrisThielemans commented
> For the SB, CMake finds a surprising version (which is then passed on)
> 
> ```
> Found Python: /opt/hostedtoolcache/Python/3.10.12/x64/bin/python3.10 (found version "3.10.12") found components: Interpreter Development Development.Module Development.Embed
> Found Python_EXECUTABLE=/opt/hostedtoolcache/Python/3.10.12/x64/bin/python3.10
> ```
> 
> The CMake strategy for selecting a python version is still far too complicated/error-prone. I suggest therefore to explicitly set `Python_EXECUTABLE=${which python}` in the Action.

This is still the case, hence the failures.

2025-03-25 12:15 UTC, casperdcl commented
Ah I finally understood; you *don't* want to use the system Python.

TL;DR we need to unset the cmake helpers defined by https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#environment-variables

2025-03-25 12:47 UTC, KrisThielemans commented
> Ah I finally understood; you _don't_ want to use the system Python.
> 
> TL;DR we need to unset [the cmake helpers defined by `actions/setup-python`](https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#environment-variables).

pretty confusing... I don't care which python is being used here, but obviously we should always use the same. As we seem to be using `setup-python` with `pip`, and then create a venv, we should be using that one. I guess that's what you did now, so ... great.

Sadly, some zenodo download issues ATM.

2025-03-25 12:48 UTC, KrisThielemans approved these changes

2025-03-25 12:48 UTC, KrisThielemans reviewed
oh. still need to update CHANGES.md!

2025-03-25 17:19 UTC, merged

2025-03-25 17:46 UTC, KrisThielemans commented
Success! Thanks @casperdcl . however, can you now have a different PR to update CHANGES.md, saying that we've switched to FindPython (maybe a link), and that they should use `Python_EXECUTABLE` or any other variables as indicated in the CMake doc? (Sorry, I shouldn't have approved the PR :-))

2025-03-25 18:31 UTC, casperdcl commented
Already updated the changelog; feel free to update further

2025-03-25 19:26 UTC, KrisThielemans commented
Sorry. Confused. Which changelog?

2025-03-25 19:33 UTC, casperdcl commented
https://github.com/SyneRBI/SIRF-SuperBuild/blob/master/CHANGES.md